from enum import Enum


class FightStep(Enum):
    NONE = 0
    BEGINNING = 1

    DEFENSE_PHASE_STARTING_MESSAGE = 2
    DEFENSE_PHASE_TEST = 3
    DEFENSE_PHASE_TEST_RESULT = 4
    DEFENSE_PHASE_SPECIAL_EFFECT = 5

    ATTACK_PHASE_STARTING_MESSAGE = 6  # unused
    ATTACK_PHASE_PICK_WEAPON = 7
    ATTACK_PHASE_TEST = 8
    ATTACK_PHASE_TEST_RESULT = 9
    ATTACK_PHASE_SPECIAL_EFFECT = 10

    CONGRATULATION_MESSAGE = 11
    DEFEAT_MESSAGE = 12
