from dataclasses import dataclass

from overworld import Ma


@dataclass
class NaiveUnit:
    map: Ma = None
    x: int = 0
    y: int = 0


@dataclass
class NaiveCompound:
    english: str
    word_1: str
    word_2: str


def get_naive_units(al):
    return {
        "คน": NaiveUnit(map=al.mas.chaiyaphum, x=800, y=711),
        "ดี": NaiveUnit(map=al.mas.chumphae, x=818, y=622),
        "ดู": NaiveUnit(map=al.mas.lomsak, x=818, y=622),
        "ใจ": NaiveUnit(map=al.mas.lomsak, x=669, y=618),
        "ยิน": NaiveUnit(map=al.mas.kasetsombum, x=790, y=655),
        "โชค": NaiveUnit(),
        "มาก": NaiveUnit(),
        "ได้": NaiveUnit(),
        "ก็": NaiveUnit(),
        "ตาม": NaiveUnit(),
        "เข้า": NaiveUnit(),
        "จำ": NaiveUnit(),
        "ความ": NaiveUnit(),
        "เป็น": NaiveUnit(),
        "คิด": NaiveUnit(),
        "เห็น": NaiveUnit(),
        "ว่า": NaiveUnit(),
        "การ": NaiveUnit(),
        "ต้อง": NaiveUnit(),
        "จัด": NaiveUnit(),
        "พิมพ์": NaiveUnit(),
        "กลุ่ม": NaiveUnit(),
        "ดาว": NaiveUnit(),
        "เทียม": NaiveUnit(),
        "ตก": NaiveUnit(),
        "น้ำ": NaiveUnit(),
        "ฝน": NaiveUnit(),
        "ปลา": NaiveUnit(),
        "ไป": NaiveUnit(),
        "เสาร์": NaiveUnit(),
        "ถึง": NaiveUnit(),
        "กับ": NaiveUnit(),
        "หา": NaiveUnit(),
        "นอก": NaiveUnit(),
        "ทุ่ง": NaiveUnit(),
        "เกี่ยว": NaiveUnit(),
        "อยู่": NaiveUnit(),
        "เดียว": NaiveUnit(),
        "เหมือน": NaiveUnit(),
        "ที่": NaiveUnit(),
        "อาศัย": NaiveUnit(),
        "ขึ้น": NaiveUnit(),
        "รอด": NaiveUnit(),
        "เอง": NaiveUnit(),
        "ทำ": NaiveUnit(),
        "ให้": NaiveUnit(),
        "งาน": NaiveUnit(),
        "บุญ": NaiveUnit(),
        "ร้าย": NaiveUnit(),
        "นา": NaiveUnit(),
        "อาหาร": NaiveUnit(),
        "ผิด": NaiveUnit(),
        "ลอง": NaiveUnit(),
        "เสี่ยง": NaiveUnit(),
        "รู้": NaiveUnit(),
        "รอบ": NaiveUnit(),
        "สึก": NaiveUnit(),
        "ลา": NaiveUnit(),
        "จัก": NaiveUnit(),
        "ผู้": NaiveUnit(),
        "ชีวิต": NaiveUnit(),
        "หญิง": NaiveUnit(),
        "ชาย": NaiveUnit(),
        "นำ": NaiveUnit(),
        "ป่วย": NaiveUnit(),
        "ใหญ่": NaiveUnit(),
        "ใช้": NaiveUnit(),
        "ครู": NaiveUnit(),
        "ส่วน": NaiveUnit(),
        "ไม้": NaiveUnit(),
        "โลก": NaiveUnit(),
        "ใบ": NaiveUnit(),
        "ตัว": NaiveUnit(),
        "ของ": NaiveUnit(),
        "ทั่ว": NaiveUnit(),
        "ร้อน": NaiveUnit(),
        "สงคราม": NaiveUnit(),
        "ชาว": NaiveUnit(),
        "ขั้ว": NaiveUnit(),
        "พื้น": NaiveUnit(),
        "บ้าน": NaiveUnit(),
        "ฤดู": NaiveUnit(),
        "พัก": NaiveUnit(),
        "ไว้": NaiveUnit(),
        "เมือง": NaiveUnit(),
        "เร่า": NaiveUnit(),
        "ไทย": NaiveUnit(),
        "หลวง": NaiveUnit(),
        "พ่อ": NaiveUnit(),
        "วัน": NaiveUnit(),
        "เกิด": NaiveUnit(),
        "ศุกร์": NaiveUnit(),
        "พระ": NaiveUnit(),
        "แม่": NaiveUnit(),
        "เหล็ก": NaiveUnit(),
        "ชี": NaiveUnit(),
        "มด": NaiveUnit(),
        "แดง": NaiveUnit(),
        "รัง": NaiveUnit(),
        "ไก่": NaiveUnit(),
        "หม้าย": NaiveUnit(),
        "ธุดงค์": NaiveUnit(),
        "เลี้ยง": NaiveUnit(),
        "ผี": NaiveUnit(),
        "เสื้อ": NaiveUnit(),
        "พุทธ": NaiveUnit(),
        "ผ้า": NaiveUnit(),
        "ตี": NaiveUnit(),
        "ธาตุ": NaiveUnit(),
        "กล้า": NaiveUnit(),
        "แก่": NaiveUnit(),
        "สร้าง": NaiveUnit(),
        "เจ้า": NaiveUnit(),
        "เก่า": NaiveUnit(),
        "ชาติ": NaiveUnit(),
        "ศิษย์": NaiveUnit(),
        "รุ่น": NaiveUnit(),
        "กรุง": NaiveUnit(),
        "เพื่อน": NaiveUnit(),
        "ยุค": NaiveUnit(),
        "ลูก": NaiveUnit(),
        "สาว": NaiveUnit(),
        "มี": NaiveUnit(),
        "ค่า": NaiveUnit(),
        "ชื่อ": NaiveUnit(),
        "เรื่อง": NaiveUnit(),
        "อายุ": NaiveUnit(),
        "หน้า": NaiveUnit(),
        "เสียง": NaiveUnit(),
        "เสือ": NaiveUnit(),
        "ปี": NaiveUnit(),
        "ดำ": NaiveUnit(),
        "ข้าง": NaiveUnit(),
        "ภาย": NaiveUnit(),
        "ฟอง": NaiveUnit(),
        "อ่อน": NaiveUnit(),
        "ช้าง": NaiveUnit(),
        "แอ": NaiveUnit(),
        "จุด": NaiveUnit(),
        "เผือก": NaiveUnit(),
        "งา": NaiveUnit(),
        "ผล": NaiveUnit(),
        "รัก": NaiveUnit(),
        "เหตุ": NaiveUnit(),
        "ก่อน": NaiveUnit(),
        "น่า": NaiveUnit(),
        "คำ": NaiveUnit(),
        "คู่": NaiveUnit(),
        "แท้": NaiveUnit(),
        "อ๊อด": NaiveUnit(),
        "หิน": NaiveUnit(),
        "ใหม่": NaiveUnit(),
        "ย้อย": NaiveUnit(),
        "ทอง": NaiveUnit(),
        "หนืด": NaiveUnit(),
        "ตู้": NaiveUnit(),
        "ไฟ": NaiveUnit(),
        "หมาย": NaiveUnit(),
        "รวม": NaiveUnit(),
        "จบ": NaiveUnit(),
        "แข็ง": NaiveUnit(),
        "ขาย": NaiveUnit(),
        "ตัด": NaiveUnit(),
        "กฎ": NaiveUnit(),
        "ฟ้า": NaiveUnit(),
        "ปิด": NaiveUnit(),
        "รถ": NaiveUnit(),
        "ป่า": NaiveUnit(),
        "ดับ": NaiveUnit(),
        "ถูก": NaiveUnit(),
        "หมู่": NaiveUnit(),
        "นี้": NaiveUnit(),
        "หอ": NaiveUnit(),
        "สิน": NaiveUnit(),
        "ศิลป์": NaiveUnit(),
        "ผ่า": NaiveUnit(),
        "ผม": NaiveUnit(),
        "ทรง": NaiveUnit(),
        "สี": NaiveUnit(),
        "จุก": NaiveUnit(),
        "กลด": NaiveUnit(),
        "ขาว": NaiveUnit(),
        "ส้ม": NaiveUnit(),
        "ทา": NaiveUnit(),
        "ราก": NaiveUnit(),
        "ปาก": NaiveUnit(),
        "ฟัน": NaiveUnit(),
        "ออก": NaiveUnit(),
        "กล้วย": NaiveUnit(),
        "ถาม": NaiveUnit(),
        "พูด": NaiveUnit(),
        "ขอ": NaiveUnit(),
        "ส่ง": NaiveUnit(),
        "เงิน": NaiveUnit(),
        "คัด": NaiveUnit(),
        "ดอก": NaiveUnit(),
        "กลีบ": NaiveUnit(),
        "จะ": NaiveUnit(),
        "แปล": NaiveUnit(),
        "เห็ด": NaiveUnit(),
        "หอม": NaiveUnit(),
        "หัว": NaiveUnit(),
        "กลิ่น": NaiveUnit(),
        "ข้อ": NaiveUnit(),
        "เราะ": NaiveUnit(),
        "ปวด": NaiveUnit(),
        "กอง": NaiveUnit(),
        "ขับ": NaiveUnit(),
        "บัส": NaiveUnit(),
        "ท้อง": NaiveUnit(),
        "หลัง": NaiveUnit(),
        "ปล่อง": NaiveUnit(),
        "ยา": NaiveUnit(),
        "เมฆ": NaiveUnit(),
    }


def get_naive_compounds():
    return [
        NaiveCompound(
            english="pain, ache",
            word_1="ความ",
            word_2="ปวด",
        ),
        NaiveCompound(
            english="to heartache",
            word_1="ปวด",
            word_2="ใจ",
        ),
        NaiveCompound(
            english="to have a backache",
            word_1="ปวด",
            word_2="หลัง",
        ),
        NaiveCompound(
            english="to have a stomachache",
            word_1="ปวด",
            word_2="ท้อง",
        ),
        NaiveCompound(
            english="pheasant",
            word_1="ไก่",
            word_2="ฟ้า",
        ),
        NaiveCompound(
            english="bus",
            word_1="ขับ",
            word_2="บัส",
        ),
        NaiveCompound(
            english="to drive",
            word_1="ขับ",
            word_2="รถ",
        ),
        NaiveCompound(
            english="chimney, smoke vent",
            word_1="ปล่อง",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="pile of merit",
            word_1="กอง",
            word_2="บุญ",
        ),
        NaiveCompound(
            english="bonfire, campfire",
            word_1="กอง",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="to have a headache",
            word_1="ปวด",
            word_2="หัว",
        ),
        NaiveCompound(
            english="boss, chief, leader",
            word_1="หัว",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="to laugh",
            word_1="หัว",
            word_2="เราะ",
        ),
        NaiveCompound(
            english="topic, subject",
            word_1="หัว",
            word_2="ข้อ",
        ),
        NaiveCompound(
            english="heart",
            word_1="หัว",
            word_2="ใจ",
        ),
        NaiveCompound(
            english="powder mixed with water to revive someone",
            word_1="ยา",
            word_2="หอม",
        ),
        NaiveCompound(
            english="onion",
            word_1="หัว",
            word_2="หอม",
        ),
        NaiveCompound(
            english="fragrance",
            word_1="ความ",
            word_2="หอม",
        ),
        NaiveCompound(
            english="perfume",
            word_1="น้ำ",
            word_2="หอม",
        ),
        NaiveCompound(
            english="to smell good",
            word_1="กลิ่น",
            word_2="หอม",
        ),
        NaiveCompound(
            english="to behead, decapitate",
            word_1="ตัด",
            word_2="หัว",
        ),
        NaiveCompound(
            english="eliminate",
            word_1="ตัด",
            word_2="ออก",
        ),
        NaiveCompound(
            english="to part with something, give up something (reluctantly)",
            word_1="ตัด",
            word_2="ใจ",
        ),
        NaiveCompound(
            english="rain cloud, nimbus",
            word_1="เมฆ",
            word_2="ฝน",
        ),
        NaiveCompound(
            english="banana",
            word_1="กล้วย",
            word_2="หอม",
        ),
        NaiveCompound(
            english="translating",
            word_1="การ",
            word_2="แปล",
        ),
        NaiveCompound(
            english="translator",
            word_1="ผู้",
            word_2="แปล",
        ),
        NaiveCompound(
            english="mushroom",
            word_1="ดอก",
            word_2="เห็ด",
        ),
        NaiveCompound(
            english="translation",
            word_1="คำ",
            word_2="แปล",
        ),
        NaiveCompound(
            english="rather, somewhat",
            word_1="ออก",
            word_2="จะ",
        ),
        NaiveCompound(
            english="gold flower / prostitute",
            word_1="ดอก",
            word_2="ทอง",
        ),
        NaiveCompound(
            english="petal, corolla",
            word_1="กลีบ",
            word_2="ดอก",
        ),
        NaiveCompound(
            english="flower",
            word_1="ดอก",
            word_2="ไม้",
        ),
        NaiveCompound(
            english="to bloom, produce flowers",
            word_1="ออก",
            word_2="ดอก",
        ),
        NaiveCompound(
            english="to sort out",
            word_1="คัด",
            word_2="ออก",
        ),
        NaiveCompound(
            english="to pay",
            word_1="ออก",
            word_2="เงิน",
        ),
        NaiveCompound(
            english="to remember, recall / to figure out a solution",
            word_1="คิด",
            word_2="ออก",
        ),
        NaiveCompound(
            english="to resign, quit, leave",
            word_1="ลา",
            word_2="ออก",
        ),
        NaiveCompound(
            english="to export, send abroad",
            word_1="ส่ง",
            word_2="ออก",
        ),
        NaiveCompound(
            english="request",
            word_1="คำ",
            word_2="ขอ",
        ),
        NaiveCompound(
            english="words, speech",
            word_1="คำ",
            word_2="พูด",
        ),
        NaiveCompound(
            english="question",
            word_1="คำ",
            word_2="ถาม",
        ),
        NaiveCompound(
            english="orchid",
            word_1="กล้วย",
            word_2="ไม้",
        ),
        NaiveCompound(
            english="to say, speak, talk",
            word_1="ออก",
            word_2="ปาก",
        ),
        NaiveCompound(
            english="estuary, mouth of a river",
            word_1="ปาก",
            word_2="น้ำ",
        ),
        NaiveCompound(
            english="root word",
            word_1="ราก",
            word_2="คำ",
        ),
        NaiveCompound(
            english="tooth root",
            word_1="ราก",
            word_2="ฟัน",
        ),
        NaiveCompound(
            english="to wear lipstick",
            word_1="ทา",
            word_2="ปาก",
        ),
        NaiveCompound(
            english="roots of hair",
            word_1="ราก",
            word_2="ผม",
        ),
        NaiveCompound(
            english="to paint",
            word_1="ทา",
            word_2="สี",
        ),
        NaiveCompound(
            english="to be orange",
            word_1="สี",
            word_2="ส้ม",
        ),
        NaiveCompound(
            english="to be golden (color)",
            word_1="สี",
            word_2="ทอง",
        ),
        NaiveCompound(
            english="to be red",
            word_1="สี",
            word_2="แดง",
        ),
        NaiveCompound(
            english="to be white",
            word_1="สี",
            word_2="ขาว",
        ),
        NaiveCompound(
            english="to have a halo",
            word_1="ทรง",
            word_2="กลด",
        ),
        NaiveCompound(
            english="topknot",
            word_1="ผม",
            word_2="จุก",
        ),
        NaiveCompound(
            english="hair color",
            word_1="สี",
            word_2="ผม",
        ),
        NaiveCompound(
            english="hairstyle, haircut",
            word_1="ทรง",
            word_2="ผม",
        ),
        NaiveCompound(
            english="to chop wood",
            word_1="ตัด",
            word_2="ไม้",
        ),
        NaiveCompound(
            english="to get a haircut, to cut hair",
            word_1="ตัด",
            word_2="ผม",
        ),
        NaiveCompound(
            english="to have surgery, to have an operation",
            word_1="ผ่า",
            word_2="ตัด",
        ),
        NaiveCompound(
            english="cutting off",
            word_1="การ",
            word_2="ตัด",
        ),
        NaiveCompound(
            english="art gallery",
            word_1="หอ",
            word_2="ศิลป์",
        ),
        NaiveCompound(
            english="monks room",
            word_1="หอ",
            word_2="พระ",
        ),
        NaiveCompound(
            english="to decide",
            word_1="ตัด",
            word_2="สิน",
        ),
        NaiveCompound(
            english="dormitory",
            word_1="หอ",
            word_2="พัก",
        ),
        NaiveCompound(
            english="recently",
            word_1="พัก",
            word_2="นี้",
        ),
        NaiveCompound(
            english="mob rule, majority power",
            word_1="กฎ",
            word_2="หมู่",
        ),
        NaiveCompound(
            english="to comply with the rules",
            word_1="ถูก",
            word_2="กฎ",
        ),
        NaiveCompound(
            english="to extinguish a fire",
            word_1="ดับ",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="forest fire",
            word_1="ไฟ",
            word_2="ป่า",
        ),
        NaiveCompound(
            english="train",
            word_1="รถ",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="spark",
            word_1="ลูก",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="to turn off the light",
            word_1="ปิด",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="red light",
            word_1="ไฟ",
            word_2="แดง",
        ),
        NaiveCompound(
            english="electricity",
            word_1="ไฟ",
            word_2="ฟ้า",
        ),
        NaiveCompound(
            english="to encompass",
            word_1="หมาย",
            word_2="รวม",
        ),
        NaiveCompound(
            english="to mean",
            word_1="หมาย",
            word_2="ถึง",
        ),
        NaiveCompound(
            english="law",
            word_1="กฎ",
            word_2="หมาย",
        ),
        NaiveCompound(
            english="center, hub",
            word_1="จุด",
            word_2="รวม",
        ),
        NaiveCompound(
            english="intersection point",
            word_1="จุด",
            word_2="ตัด",
        ),
        NaiveCompound(
            english="selling point",
            word_1="จุด",
            word_2="ขาย",
        ),
        NaiveCompound(
            english="strength, good point",
            word_1="จุด",
            word_2="แข็ง",
        ),
        NaiveCompound(
            english="end, end point",
            word_1="จุด",
            word_2="จบ",
        ),
        NaiveCompound(
            english="goal, aim, purpose",
            word_1="จุด",
            word_2="หมาย",
        ),
        NaiveCompound(
            english="ignite",
            word_1="จุด",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="aquarium",
            word_1="ตู้",
            word_2="ปลา",
        ),
        NaiveCompound(
            english="magma",
            word_1="หิน",
            word_2="หนืด",
        ),
        NaiveCompound(
            english="goldfish",
            word_1="ปลา",
            word_2="แดง",
        ),
        NaiveCompound(
            english="copper",
            word_1="ทอง",
            word_2="แดง",
        ),
        NaiveCompound(
            english="gold",
            word_1="ทอง",
            word_2="คำ",
        ),
        NaiveCompound(
            english="say goodbye, leave",
            word_1="ลา",
            word_2="ก่อน",
        ),
        NaiveCompound(
            english="wait and see, see what happens",
            word_1="ดู",
            word_2="ก่อน",
        ),
        NaiveCompound(
            english="last year",
            word_1="ปี",
            word_2="ก่อน",
        ),
        NaiveCompound(
            english="golden age",
            word_1="ยุค",
            word_2="ทอง",
        ),
        NaiveCompound(
            english="stalactite",
            word_1="หิน",
            word_2="ย้อย",
        ),
        NaiveCompound(
            english="new model",
            word_1="รุ่น",
            word_2="ใหม่",
        ),
        NaiveCompound(
            english="stone age",
            word_1="ยุค",
            word_2="หิน",
        ),
        NaiveCompound(
            english="tadpole",
            word_1="ลูก",
            word_2="อ๊อด",
        ),
        NaiveCompound(
            english="globe",
            word_1="ลูก",
            word_2="โลก",
        ),
        NaiveCompound(
            english="true love",
            word_1="รัก",
            word_2="แท้",
        ),
        NaiveCompound(
            english="to be diligent, persevering",
            word_1="รัก",
            word_2="ดี",
        ),
        NaiveCompound(
            english="valued friend, bosom friend, close friend",
            word_1="เพื่อน",
            word_2="รัก",
        ),
        NaiveCompound(
            english="to be extremely fond of, to love, to be bent on",
            word_1="ใจ",
            word_2="รัก",
        ),
        NaiveCompound(
            english="patriotic",
            word_1="รัก",
            word_2="ชาติ",
        ),
        NaiveCompound(
            english="lover, boyfriend, girlfriend",
            word_1="คู่",
            word_2="รัก",
        ),
        NaiveCompound(
            english="lover, darling",
            word_1="คน",
            word_2="รัก",
        ),
        NaiveCompound(
            english="cute, attractive, pretty",
            word_1="น่า",
            word_2="รัก",
        ),
        NaiveCompound(
            english="love",
            word_1="ความ",
            word_2="รัก",
        ),
        NaiveCompound(
            english="reason",
            word_1="เหตุ",
            word_2="ผล",
        ),
        NaiveCompound(
            english="sweetheart (talking to one's child)",
            word_1="ลูก",
            word_2="รัก",
        ),
        NaiveCompound(
            english="works / success, accomplishment, achievement",
            word_1="ผล",
            word_2="งาน",
        ),
        NaiveCompound(
            english="big project",
            word_1="งาน",
            word_2="ช้าง",
        ),
        NaiveCompound(
            english="elephant ivory tusk",
            word_1="งา",
            word_2="ช้าง",
        ),
        NaiveCompound(
            english="white (albino) elephant",
            word_1="ช้าง",
            word_2="เผือก",
        ),
        NaiveCompound(
            english="to diminish, lessen, reduce",
            word_1="อ่อน",
            word_2="ตัว",
        ),
        NaiveCompound(
            english="weakness",
            word_1="ความ",
            word_2="อ่อน",
        ),
        NaiveCompound(
            english="weak point",
            word_1="จุด",
            word_2="อ่อน",
        ),
        NaiveCompound(
            english="to be weak, feeble, tired",
            word_1="อ่อน",
            word_2="แอ",
        ),
        NaiveCompound(
            english="elephant calf",
            word_1="ลูก",
            word_2="ช้าง",
        ),
        NaiveCompound(
            english="mosquito larva",
            word_1="ลูก",
            word_2="น้ำ",
        ),
        NaiveCompound(
            english="baby, infant",
            word_1="ลูก",
            word_2="อ่อน",
        ),
        NaiveCompound(
            english="chick, baby chicken",
            word_1="ลูก",
            word_2="ไก่",
        ),
        NaiveCompound(
            english="sponge",
            word_1="ฟอง",
            word_2="น้ำ",
        ),
        NaiveCompound(
            english="to bubble, to foam",
            word_1="เป็น",
            word_2="ฟอง",
        ),
        NaiveCompound(
            english="future",
            word_1="ภาย",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="to precede, to lead",
            word_1="นำ",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="next year, coming year",
            word_1="ปี",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="in front",
            word_1="ข้าง",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="panther",
            word_1="เสือ",
            word_2="ดำ",
        ),
        NaiveCompound(
            english="leopard",
            word_1="เสือ",
            word_2="ดาว",
        ),
        NaiveCompound(
            english="year of the tiger",
            word_1="ปี",
            word_2="เสือ",
        ),
        NaiveCompound(
            english="boy scout",
            word_1="ลูก",
            word_2="เสือ",
        ),
        NaiveCompound(
            english="to have a voice, to be entitled to vote",
            word_1="มี",
            word_2="เสียง",
        ),
        NaiveCompound(
            english="to dare to, to be shameless",
            word_1="มี",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="to abound, to be found everywhere",
            word_1="มี",
            word_2="มาก",
        ),
        NaiveCompound(
            english="to be aged",
            word_1="มี",
            word_2="อายุ",
        ),
        NaiveCompound(
            english="to get into trouble, to quarrel",
            word_1="มี",
            word_2="เรื่อง",
        ),
        NaiveCompound(
            english="well-known",
            word_1="มี",
            word_2="ชื่อ",
        ),
        NaiveCompound(
            english="valuable, precious",
            word_1="มี",
            word_2="ค่า",
        ),
        NaiveCompound(
            english="to raise children, to bring up a child",
            word_1="เลี้ยง",
            word_2="ลูก",
        ),
        NaiveCompound(
            english="uterus, womb",
            word_1="มด",
            word_2="ลูก",
        ),
        NaiveCompound(
            english="to have children",
            word_1="มี",
            word_2="ลูก",
        ),
        NaiveCompound(
            english="son",
            word_1="ลูก",
            word_2="ชาย",
        ),
        NaiveCompound(
            english="daughter",
            word_1="ลูก",
            word_2="สาว",
        ),
        NaiveCompound(
            english="student, disciple, pupil",
            word_1="ลูก",
            word_2="ศิษย์",
        ),
        NaiveCompound(
            english="ancient, old, legendary",
            word_1="เก่า",
            word_2="ก่อน",
        ),
        NaiveCompound(
            english="older times, former times",
            word_1="ยุค",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="old friend",
            word_1="เพื่อน",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="old capital",
            word_1="กรุง",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="old generation",
            word_1="รุ่น",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="alumni, alumnus",
            word_1="ศิษย์",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="antique",
            word_1="ของ",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="ancient, old, former",
            word_1="เก่า",
            word_2="แก่"
        ),
        NaiveCompound(english="national", word_1="ของ", word_2="ชาติ"),
        NaiveCompound(english="owner", word_1="เจ้า", word_2="ของ"),
        NaiveCompound(english="original", word_1="เจ้า", word_2="เก่า"),
        NaiveCompound(english="homeowner", word_1="เจ้า", word_2="บ้าน"),
        NaiveCompound(english="to build a house", word_1="สร้าง", word_2="บ้าน"),
        NaiveCompound(
            english="homeland, hometown, native village", word_1="บ้าน", word_2="เกิด"
        ),
        NaiveCompound(
            english="to be at home, stay at home", word_1="อยู่", word_2="อยู่"
        ),
        NaiveCompound(english="country, state, nation", word_1="บ้าน", word_2="เมือง"),
        NaiveCompound(
            english="villager, folk, ordinary people", word_1="ชาว", word_2="บ้าน"
        ),
        NaiveCompound(english="aging", word_1="ความ", word_2="แก่"),
        NaiveCompound(english="old people", word_1="คน", word_2="แก่"),
        NaiveCompound(english="to think of", word_1="เห็น", word_2="แก่"),
        NaiveCompound(english="courage", word_1="ความ", word_2="กล้า"),
        NaiveCompound(english="to be highly skillful in", word_1="แก่", word_2="กล้า"),
        NaiveCompound(english="steel", word_1="เหล็ก", word_2="กล้า"),
        NaiveCompound(english="iron", word_1="ธาตุ", word_2="เหล็ก"),
        NaiveCompound(english="to forge iron", word_1="ตี", word_2="เหล็ก"),
        NaiveCompound(english="water demon", word_1="เสื้อ", word_2="น้ำ"),
        NaiveCompound(english="clothes", word_1="เสื้อ", word_2="ผ้า"),
        NaiveCompound(english="Buddha", word_1="พระ", word_2="พุทธ"),
        NaiveCompound(english="butterfly", word_1="ผี", word_2="เสื้อ"),
        NaiveCompound(
            english="to offer sacrifices to a spirit", word_1="เลี้ยง", word_2="ผี"
        ),
        NaiveCompound(
            english="to offer food (to a monk)", word_1="เลี้ยง", word_2="พระ"
        ),
        NaiveCompound(english="monk on pilgrimage", word_1="พระ", word_2="ธุดงค์"),
        NaiveCompound(english="widow", word_1="แม่", word_2="หม้าย"),
        NaiveCompound(english="hen", word_1="แม่", word_2="ไก่"),
        NaiveCompound(english="ant nest", word_1="รัง", word_2="มด"),
        NaiveCompound(english="red ant", word_1="มด", word_2="แดง"),
        NaiveCompound(english="witch", word_1="แม่", word_2="มด"),
        NaiveCompound(english="nun", word_1="แม่", word_2="ชี"),
        NaiveCompound(english="housewife", word_1="แม่", word_2="บ้าน"),
        NaiveCompound(english="magnet", word_1="แม่", word_2="เหล็ก"),
        NaiveCompound(english="parents", word_1="พ่อ", word_2="แม่"),
        NaiveCompound(english="river", word_1="แม่", word_2="น้ำ"),
        NaiveCompound(english="kind-hearted woman", word_1="แม่", word_2="พระ"),
        NaiveCompound(english="Buddhist holiday", word_1="วัน", word_2="พระ"),
        NaiveCompound(english="Friday", word_1="วัน", word_2="ศุกร์"),
        NaiveCompound(english="birthday", word_1="วัน", word_2="เกิด"),
        NaiveCompound(english="Saturday", word_1="วัน", word_2="เสาร์"),
        NaiveCompound(english="venerable monk", word_1="หลวง", word_2="พ่อ"),
        NaiveCompound(english="city person", word_1="คน", word_2="เมือง"),
        NaiveCompound(english="capital city", word_1="เมือง", word_2="หลวง"),
        NaiveCompound(english="Thailand", word_1="เมือง", word_2="ไทย"),
        NaiveCompound(
            english="to be anxious, be worried", word_1="เร่า", word_2="ร้อน"
        ),
        NaiveCompound(english="tropical country", word_1="เมือง", word_2="ร้อน"),
        NaiveCompound(english="to stop, pause, stay", word_1="พัก", word_2="ไว้"),
        NaiveCompound(english="to stay overnight", word_1="พัก", word_2="อยู่"),
        NaiveCompound(english="to have a holiday", word_1="พัก", word_2="ร้อน"),
        NaiveCompound(english="summer", word_1="ฤดู", word_2="ร้อน"),
        NaiveCompound(english="hot water", word_1="น้ำ", word_2="ร้อน"),
        NaiveCompound(english="heat", word_1="ความ", word_2="ร้อน"),
        NaiveCompound(english="to worry, be anxious", word_1="ร้อน", word_2="ใจ"),
        NaiveCompound(english="local, folk, homegrown", word_1="พื้น", word_2="บ้าน"),
        NaiveCompound(english="area, district, place", word_1="พื้น", word_2="ที่"),
        NaiveCompound(english="surface of the water", word_1="พื้น", word_2="น้ำ"),
        NaiveCompound(english="the Earth's surface", word_1="พื้น", word_2="โลก"),
        NaiveCompound(english="pole (north, south)", word_1="ขั้ว", word_2="โลก"),
        NaiveCompound(english="world population", word_1="ชาว", word_2="โลก"),
        NaiveCompound(english="world war", word_1="สงคราม", word_2="โลก"),
        NaiveCompound(english="global warming", word_1="โลก", word_2="ร้อน"),
        NaiveCompound(english="worldwide", word_1="ทั่ว", word_2="โลก"),
        NaiveCompound(english="worldly, material, fleshy", word_1="ของ", word_2="โลก"),
        NaiveCompound(english="leaf", word_1="ใบ", word_2="ไม้"),
        NaiveCompound(english="around the world", word_1="รอบ", word_2="โลก"),
        NaiveCompound(english="tree", word_1="ไม้", word_2="ใหญ่"),
        NaiveCompound(english="majority", word_1="ส่วน", word_2="ใหญ่"),
        NaiveCompound(english="headmaster", word_1="ครู", word_2="ใหญ่"),
        NaiveCompound(
            english="to be intimate / to know the mind", word_1="รู้", word_2="ใจ"
        ),
        NaiveCompound(english="user", word_1="ผู้", word_2="ใช้"),
        NaiveCompound(english="adult, senior, elder", word_1="ผู้", word_2="ใหญ่"),
        NaiveCompound(
            english="patient, sufferer, sick person", word_1="ผู้", word_2="ป่วย"
        ),
        NaiveCompound(english="leader, chief, captain", word_1="ผู้", word_2="นำ"),
        NaiveCompound(english="man", word_1="ผู้", word_2="ชาย"),
        NaiveCompound(english="woman", word_1="ผู้", word_2="หญิง"),
        NaiveCompound(english="to risk, jeopardize", word_1="เสี่ยง", word_2="ชีวิต"),
        NaiveCompound(
            english="knowledgeable people, well-informed people",
            word_1="ผู้",
            word_2="รู้",
        ),
        NaiveCompound(english="to let someone know", word_1="ให้", word_2="รู้"),
        NaiveCompound(english="to know (someone)", word_1="รู้", word_2="จัก"),
        NaiveCompound(
            english="knowledge, information, awareness", word_1="ความ", word_2="รู้"
        ),
        NaiveCompound(english="to leave the monkhood", word_1="ลา", word_2="สึก"),
        NaiveCompound(english="to feel, touch", word_1="รู้", word_2="สึก"),
        NaiveCompound(english="all around", word_1="รอบ", word_2="ตัว"),
        NaiveCompound(english="to be aware, conscious of", word_1="รู้", word_2="ตัว"),
        NaiveCompound(english="to take the risk", word_1="ลอง", word_2="เสี่ยง"),
        NaiveCompound(english="to try out", word_1="ลอง", word_2="ดู"),
        NaiveCompound(
            english="to reproduce, make a copy, imitate", word_1="จำ", word_2="ลอง"
        ),
        NaiveCompound(english="to test, experiment, try", word_1="ลอง", word_2="ทำ"),
        NaiveCompound(
            english="to come to terms with, to accept", word_1="ทำ", word_2="ใจ"
        ),
        NaiveCompound(
            english="to make a mistake, do something wrong", word_1="ทำ", word_2="ผิด"
        ),
        NaiveCompound(english="to cook", word_1="ทำ", word_2="อาหาร"),
        NaiveCompound(english="to farm", word_1="ทำ", word_2="นา"),
        NaiveCompound(english="to imitate, copy / to obey", word_1="ทำ", word_2="ตาม"),
        NaiveCompound(english="to hurt, to do harm", word_1="ทำ", word_2="ร้าย"),
        NaiveCompound(english="to cause trouble", word_1="ทำ", word_2="ความ"),
        NaiveCompound(english="to pretend, feign", word_1="ทำ", word_2="เป็น"),
        NaiveCompound(english="to make merit", word_1="ทำ", word_2="บุญ"),
        NaiveCompound(english="to work", word_1="ทำ", word_2="งาน"),
        NaiveCompound(
            english="to cause, to make somebody do something", word_1="ทำ", word_2="ให้"
        ),
        NaiveCompound(
            english="to behave, conduct oneself, act", word_1="ทำ", word_2="ตัว"
        ),
        NaiveCompound(english="oneself, ourselves", word_1="ตัว", word_2="เอง"),
        NaiveCompound(english="to be stable, steady", word_1="อยู่", word_2="ตัว"),
        NaiveCompound(english="to survive, exist", word_1="อยู่", word_2="รอด"),
        NaiveCompound(
            english="to learn by heart, memorize", word_1="ขึ้น", word_2="ใจ"
        ),
        NaiveCompound(english="to depend on, rely on", word_1="ขึ้น", word_2="อยู่"),
        NaiveCompound(english="to live, reside", word_1="อาศัย", word_2="อยู่"),
        NaiveCompound(english="address", word_1="ที่", word_2="อยู่"),
        NaiveCompound(
            english="like, as, such as, as if", word_1="เหมือน", word_2="กับ"
        ),
        NaiveCompound(english="the same as", word_1="เดียว", word_2="กับ"),
        NaiveCompound(
            english="to be with, stay with, be with", word_1="อยู่", word_2="กับ"
        ),
        NaiveCompound(english="about, regarding", word_1="เกี่ยว", word_2="กับ"),
        NaiveCompound(english="to go to the toilet", word_1="ไป", word_2="ทุ่ง"),
        NaiveCompound(english="to go overseas", word_1="ไป", word_2="นอก"),
        NaiveCompound(english="going", word_1="การ", word_2="ไป"),
        NaiveCompound(english="to go with, accompany", word_1="ไป", word_2="กับ"),
        NaiveCompound(english="to go to see, visit, meet", word_1="ไป", word_2="หา"),
        NaiveCompound(english="to go and see", word_1="ไป", word_2="ดู"),
        NaiveCompound(english="to arrive at, to reach", word_1="ไป", word_2="ถึง"),
        NaiveCompound(english="Saturn", word_1="ดาว", word_2="เสาร์"),
        NaiveCompound(
            english="to be rejected, to be defeated, be settled",
            word_1="ตก",
            word_2="ไป",
        ),
        NaiveCompound(english="to angle, to fish", word_1="ตก", word_2="ปลา"),
        NaiveCompound(english="to be startled, shocked", word_1="ตก", word_2="ใจ"),
        NaiveCompound(english="rain", word_1="ฝน", word_2="ตก"),
        NaiveCompound(english="waterfall", word_1="น้ำ", word_2="ตก"),
        NaiveCompound(english="meteor, shooting star", word_1="ดาว", word_2="ตก"),
        NaiveCompound(english="satellite", word_1="ดาว", word_2="เทียม"),
        NaiveCompound(english="constellation", word_1="กลุ่ม", word_2="ดาว"),
        NaiveCompound(english="crowd, group of people", word_1="กลุ่ม", word_2="คน"),
        NaiveCompound(english="to form into groups", word_1="จัด", word_2="กลุ่ม"),
        NaiveCompound(english="to publish", word_1="จัด", word_2="พิมพ์"),
        NaiveCompound(english="to worry, think too much", word_1="คิด", word_2="มาก"),
        NaiveCompound(english="to manage, deal, handle", word_1="จัด", word_2="การ"),
        NaiveCompound(english="to want, need, require", word_1="ต้อง", word_2="การ"),
        NaiveCompound(
            english="to succeed, accomplish, complete", word_1="เป็น", word_2="การ"
        ),
        NaiveCompound(english="thought, thinking", word_1="การ", word_2="คิด"),
        NaiveCompound(english="thought, idea, notion", word_1="ความ", word_2="คิด"),
        NaiveCompound(english="to think that", word_1="คิด", word_2="ว่า"),
        NaiveCompound(
            english="to comment, discuss, criticize", word_1="คิด", word_2="เห็น"
        ),
        NaiveCompound(
            english="to realize, become aware of, comprehend",
            word_1="คิด",
            word_2="ได้",
        ),
        NaiveCompound(english="possibly, likely, maybe", word_1="เป็น", word_2="ได้"),
        NaiveCompound(english="memory, remembrance", word_1="ความ", word_2="จำ"),
        NaiveCompound(english="to remember", word_1="จำ", word_2="ได้"),
        NaiveCompound(english="to understand", word_1="เข้า", word_2="ใจ"),
        NaiveCompound(english="to understand", word_1="เข้า", word_2="ใจ"),
        NaiveCompound(english="good person/darling, honey", word_1="คน", word_2="ดี"),
        NaiveCompound(english="very good, excellent", word_1="ดี", word_2="มาก"),
        NaiveCompound(english="lucky/good luck!", word_1="โชค", word_2="ดี"),
        NaiveCompound(english="no matter, whatever", word_1="ก็", word_2="ตาม"),
        NaiveCompound(english="to be quite good, not bad", word_1="ก็", word_2="ดี"),
        NaiveCompound(english="ok, all right, fine", word_1="ก็", word_2="ได้"),
        NaiveCompound(
            english="audience, spectator, onlooker", word_1="คน", word_2="ดู"
        ),
        NaiveCompound(english="to look good", word_1="ดู", word_2="ดี"),
        NaiveCompound(english="to be nice", word_1="ใจ", word_2="ดี"),
        NaiveCompound(english="to be glad", word_1="ยิน", word_2="ดี"),
        NaiveCompound(english="to hear", word_1="ได้", word_2="ยิน"),
    ]


# def get_links_from_city_word(current_word: str, al):
#     city_words = get_city_words(al)
#     near_city_words = []
#     for aggregate in AGGREGATES:
#         if current_word in aggregate["words"]:
#             for word in aggregate["words"]:
#                 if word != current_word:
#                     near_city_words.append({
#                         "english": aggregate["english"],
#                         "thai": aggregate["thai"],
#                         "words": aggregate["words"],
#                         "city": city_words[word],
#                     })
#     # al.aggregates = near_city_words
#     for near_city_word in near_city_words:
#         print(near_city_word)
