from dataclasses import dataclass

from overworld import Ma


@dataclass
class NaiveUnit:
    map: Ma = None
    x: int = 0
    y: int = 0


@dataclass
class NaiveCompound:
    english: str
    word_1: str
    word_2: str


def get_naive_units(al):
    return {
        "คน": NaiveUnit(map=al.mas.chaiyaphum, x=800, y=711),
        "ดี": NaiveUnit(map=al.mas.chumphae, x=818, y=622),
        "ดู": NaiveUnit(map=al.mas.lomsak, x=818, y=622),
        "ใจ": NaiveUnit(map=al.mas.lomsak, x=669, y=618),
        "ยิน": NaiveUnit(map=al.mas.kasetsombum, x=790, y=655),
        "โชค": NaiveUnit(),
        "มาก": NaiveUnit(),
        "ได้": NaiveUnit(),
        "ก็": NaiveUnit(),
        "ตาม": NaiveUnit(),
        "เข้า": NaiveUnit(),
        "จำ": NaiveUnit(),
        "ความ": NaiveUnit(),
        "เป็น": NaiveUnit(),
        "คิด": NaiveUnit(),
        "เห็น": NaiveUnit(),
        "ว่า": NaiveUnit(),
        "การ": NaiveUnit(),
        "ต้อง": NaiveUnit(),
        "จัด": NaiveUnit(),
        "พิมพ์": NaiveUnit(),
        "กลุ่ม": NaiveUnit(),
        "ดาว": NaiveUnit(),
        "เทียม": NaiveUnit(),
        "ตก": NaiveUnit(),
        "น้ำ": NaiveUnit(),
        "ฝน": NaiveUnit(),
        "ปลา": NaiveUnit(),
        "ไป": NaiveUnit(),
        "เสาร์": NaiveUnit(),
        "ถึง": NaiveUnit(),
        "กับ": NaiveUnit(),
        "หา": NaiveUnit(),
        "นอก": NaiveUnit(),
        "ทุ่ง": NaiveUnit(),
        "เกี่ยว": NaiveUnit(),
        "อยู่": NaiveUnit(),
        "เดียว": NaiveUnit(),
        "เหมือน": NaiveUnit(),
        "ที่": NaiveUnit(),
        "อาศัย": NaiveUnit(),
        "ขึ้น": NaiveUnit(),
        "รอด": NaiveUnit(),
        "เอง": NaiveUnit(),
        "ทำ": NaiveUnit(),
        "ให้": NaiveUnit(),
        "งาน": NaiveUnit(),
        "บุญ": NaiveUnit(),
        "ร้าย": NaiveUnit(),
        "นา": NaiveUnit(),
        "อาหาร": NaiveUnit(),
        "ผิด": NaiveUnit(),
        "ลอง": NaiveUnit(),
        "เสี่ยง": NaiveUnit(),
        "รู้": NaiveUnit(),
        "รอบ": NaiveUnit(),
        "สึก": NaiveUnit(),
        "ลา": NaiveUnit(),
        "จัก": NaiveUnit(),
        "ผู้": NaiveUnit(),
        "ชีวิต": NaiveUnit(),
        "หญิง": NaiveUnit(),
        "ชาย": NaiveUnit(),
        "นำ": NaiveUnit(),
        "ป่วย": NaiveUnit(),
        "ใหญ่": NaiveUnit(),
        "ใช้": NaiveUnit(),
        "ครู": NaiveUnit(),
        "ส่วน": NaiveUnit(),
        "ไม้": NaiveUnit(),
        "โลก": NaiveUnit(),
        "ใบ": NaiveUnit(),
        "ตัว": NaiveUnit(),
        "ของ": NaiveUnit(),
        "ทั่ว": NaiveUnit(),
        "ร้อน": NaiveUnit(),
        "สงคราม": NaiveUnit(),
        "ชาว": NaiveUnit(),
        "ขั้ว": NaiveUnit(),
        "พื้น": NaiveUnit(),
        "บ้าน": NaiveUnit(),
        "ฤดู": NaiveUnit(),
        "พัก": NaiveUnit(),
        "ไว้": NaiveUnit(),
        "เมือง": NaiveUnit(),
        "เร่า": NaiveUnit(),
        "ไทย": NaiveUnit(),
        "หลวง": NaiveUnit(),
        "พ่อ": NaiveUnit(),
        "วัน": NaiveUnit(),
        "เกิด": NaiveUnit(),
        "ศุกร์": NaiveUnit(),
        "พระ": NaiveUnit(),
        "แม่": NaiveUnit(),
        "เหล็ก": NaiveUnit(),
        "ชี": NaiveUnit(),
        "มด": NaiveUnit(),
        "แดง": NaiveUnit(),
        "รัง": NaiveUnit(),
        "ไก่": NaiveUnit(),
        "หม้าย": NaiveUnit(),
        "ธุดงค์": NaiveUnit(),
        "เลี้ยง": NaiveUnit(),
        "ผี": NaiveUnit(),
        "เสื้อ": NaiveUnit(),
        "พุทธ": NaiveUnit(),
        "ผ้า": NaiveUnit(),
        "ตี": NaiveUnit(),
        "ธาตุ": NaiveUnit(),
        "กล้า": NaiveUnit(),
        "แก่": NaiveUnit(),
        "สร้าง": NaiveUnit(),
        "เจ้า": NaiveUnit(),
        "เก่า": NaiveUnit(),
        "ชาติ": NaiveUnit(),
        "ศิษย์": NaiveUnit(),
        "รุ่น": NaiveUnit(),
        "กรุง": NaiveUnit(),
        "เพื่อน": NaiveUnit(),
        "ยุค": NaiveUnit(),
        "ลูก": NaiveUnit(),
        "สาว": NaiveUnit(),
        "มี": NaiveUnit(),
        "ค่า": NaiveUnit(),
        "ชื่อ": NaiveUnit(),
        "เรื่อง": NaiveUnit(),
        "อายุ": NaiveUnit(),
        "หน้า": NaiveUnit(),
        "เสียง": NaiveUnit(),
        "เสือ": NaiveUnit(),
        "ปี": NaiveUnit(),
        "ดำ": NaiveUnit(),
        "ข้าง": NaiveUnit(),
        "ภาย": NaiveUnit(),
        "ฟอง": NaiveUnit(),
        "อ่อน": NaiveUnit(),
        "ช้าง": NaiveUnit(),
        "แอ": NaiveUnit(),
        "จุด": NaiveUnit(),
        "เผือก": NaiveUnit(),
        "งา": NaiveUnit(),
        "ผล": NaiveUnit(),
        "รัก": NaiveUnit(),
        "เหตุ": NaiveUnit(),
        "ก่อน": NaiveUnit(),
        "น่า": NaiveUnit(),
        "คำ": NaiveUnit(),
        "คู่": NaiveUnit(),
        "แท้": NaiveUnit(),
        "อ๊อด": NaiveUnit(),
        "หิน": NaiveUnit(),
        "ใหม่": NaiveUnit(),
        "ย้อย": NaiveUnit(),
        "ทอง": NaiveUnit(),
        "หนืด": NaiveUnit(),
        "ตู้": NaiveUnit(),
        "ไฟ": NaiveUnit(),
        "หมาย": NaiveUnit(),
        "รวม": NaiveUnit(),
        "จบ": NaiveUnit(),
        "แข็ง": NaiveUnit(),
        "ขาย": NaiveUnit(),
        "ตัด": NaiveUnit(),
        "กฎ": NaiveUnit(),
        "ฟ้า": NaiveUnit(),
        "ปิด": NaiveUnit(),
        "รถ": NaiveUnit(),
        "ป่า": NaiveUnit(),
        "ดับ": NaiveUnit(),
        "ถูก": NaiveUnit(),
        "หมู่": NaiveUnit(),
        "นี้": NaiveUnit(),
        "หอ": NaiveUnit(),
        "สิน": NaiveUnit(),
        "ศิลป์": NaiveUnit(),
        "ผ่า": NaiveUnit(),
        "ผม": NaiveUnit(),
        "ทรง": NaiveUnit(),
        "สี": NaiveUnit(),
        "จุก": NaiveUnit(),
        "กลด": NaiveUnit(),
        "ขาว": NaiveUnit(),
        "ส้ม": NaiveUnit(),
        "ทา": NaiveUnit(),
        "ราก": NaiveUnit(),
        "ปาก": NaiveUnit(),
        "ฟัน": NaiveUnit(),
        "ออก": NaiveUnit(),
        "กล้วย": NaiveUnit(),
        "ถาม": NaiveUnit(),
        "พูด": NaiveUnit(),
        "ขอ": NaiveUnit(),
        "ส่ง": NaiveUnit(),
        "เงิน": NaiveUnit(),
        "คัด": NaiveUnit(),
        "ดอก": NaiveUnit(),
        "กลีบ": NaiveUnit(),
        "จะ": NaiveUnit(),
        "แปล": NaiveUnit(),
        "เห็ด": NaiveUnit(),
        "หอม": NaiveUnit(),
        "หัว": NaiveUnit(),
        "กลิ่น": NaiveUnit(),
        "ข้อ": NaiveUnit(),
        "เราะ": NaiveUnit(),
        "ปวด": NaiveUnit(),
        "กอง": NaiveUnit(),
        "ขับ": NaiveUnit(),
        "บัส": NaiveUnit(),
        "ท้อง": NaiveUnit(),
        "หลัง": NaiveUnit(),
        "ปล่อง": NaiveUnit(),
        "ยา": NaiveUnit(),
        "เมฆ": NaiveUnit(),
        "พ้อง": NaiveUnit(),
        "พวก": NaiveUnit(),
        "มวล": NaiveUnit(),
        "ภาษา": NaiveUnit(),
        "มนุษย์": NaiveUnit(),
        "กบ": NaiveUnit(),
        "คุย": NaiveUnit(),
        "ห้อง": NaiveUnit(),
        "ราคา": NaiveUnit(),
        "ขี้": NaiveUnit(),
        "ลด": NaiveUnit(),
        "ตลาด": NaiveUnit(),
        "อังกฤษ": NaiveUnit(),
        "จีน": NaiveUnit(),
        "ญี่ปุ่น": NaiveUnit(),
        "เขียน": NaiveUnit(),
        "บาลี": NaiveUnit(),
        "สันสกฤต": NaiveUnit(),
        "มลายู": NaiveUnit(),
        "พม่า": NaiveUnit(),
        "กลาง": NaiveUnit(),
        "ศาสตร์": NaiveUnit(),
        "กล": NaiveUnit(),
        "ไก": NaiveUnit(),
        "สับ": NaiveUnit(),
        "หมู": NaiveUnit(),
        "แฮม": NaiveUnit(),
        "ย่าง": NaiveUnit(),
        "ปืน": NaiveUnit(),
        "มือ": NaiveUnit(),
        "ดิน": NaiveUnit(),
        "วิทยา": NaiveUnit(),
        "เครื่อง": NaiveUnit(),
        "ถือ": NaiveUnit(),
        "สอง": NaiveUnit(),
        "จับ": NaiveUnit(),
        "ขวา": NaiveUnit(),
        "ฝ่า": NaiveUnit(),
        "นิ้ว": NaiveUnit(),
        "ซ้าย": NaiveUnit(),
        "ดีด": NaiveUnit(),
        "ลาย": NaiveUnit(),
        "สือ": NaiveUnit(),
        "ถุง": NaiveUnit(),
        "เท้า": NaiveUnit(),
        "พลาสติก": NaiveUnit(),
        "ยาง": NaiveUnit(),
        "สวน": NaiveUnit(),
        "รัด": NaiveUnit(),
        "สุด": NaiveUnit(),
        "เกล้า": NaiveUnit(),
        "ร่ม": NaiveUnit(),
        "ยอด": NaiveUnit(),
        "เย็น": NaiveUnit(),
        "ต่อ": NaiveUnit(),
        "คราว": NaiveUnit(),
        "เวลา": NaiveUnit(),
        "หนาว": NaiveUnit(),
        "ลม": NaiveUnit(),
        "ชา": NaiveUnit(),
        "ทะเล": NaiveUnit(),
        "สนาม": NaiveUnit(),
        "บิน": NaiveUnit(),
        "รบ": NaiveUnit(),
        "นัก": NaiveUnit(),
        "ลง": NaiveUnit(),
        "จาน": NaiveUnit(),
        "ล้าง": NaiveUnit(),
        "ตอบ": NaiveUnit(),
        "กลับ": NaiveUnit(),
        "ทาง": NaiveUnit(),
        "ด่า": NaiveUnit(),
        "เดิน": NaiveUnit(),
        "เส้น": NaiveUnit(),
        "ปลาย": NaiveUnit(),
        "ใน": NaiveUnit(),
        "เยอรมัน": NaiveUnit(),
        "ฝรั่งเศส": NaiveUnit(),
        "ถิ่น": NaiveUnit(),
        "ขณะ": NaiveUnit(),
        "เรียน": NaiveUnit(),
        "นอน": NaiveUnit(),
        "สมุด": NaiveUnit(),
        "ครัว": NaiveUnit(),
        "เกาหลี": NaiveUnit(),
        "สเปน": NaiveUnit(),
        "เมื่อ": NaiveUnit(),
        "แขก": NaiveUnit(),
        "พี่": NaiveUnit(),
        "น้อง": NaiveUnit(),
        "สะใภ้": NaiveUnit(),
        "งำ": NaiveUnit(),
        "มุ้ง": NaiveUnit(),
        "น้า": NaiveUnit(),
        "ครอบ": NaiveUnit(),
        "เด็ก": NaiveUnit(),
        "เพศ": NaiveUnit(),
        "สัตว์": NaiveUnit(),
        "เปลี่ยน": NaiveUnit(),
        "ศึกษา": NaiveUnit(),
        "บุตร": NaiveUnit(),
        "สถาน": NaiveUnit(),
        "ประถม": NaiveUnit(),
        "กรณี": NaiveUnit(),
        "อุดม": NaiveUnit(),
        "ภาพ": NaiveUnit(),
        "เตรียม": NaiveUnit(),
        "การณ์": NaiveUnit(),
        "แปลง": NaiveUnit(),
        "คุณ": NaiveUnit(),
        "ฉกรรจ์": NaiveUnit(),
        "โสด": NaiveUnit(),
        "ชู้": NaiveUnit(),
        "เดิม": NaiveUnit(),
        "แบบ": NaiveUnit(),
        "นาง": NaiveUnit(),
        "ง่าย": NaiveUnit(),
        "ใด": NaiveUnit(),
        "นั้น": NaiveUnit(),
        "รูป": NaiveUnit(),
        "ตา": NaiveUnit(),
        "หลาน": NaiveUnit(),
        "กัน": NaiveUnit(),
        "ร่วม": NaiveUnit(),
        "ต่าง": NaiveUnit(),
        "หาด": NaiveUnit(),
        "ทราย": NaiveUnit(),
        "กระดาษ": NaiveUnit(),
        "เม็ด": NaiveUnit(),
        "เนิน": NaiveUnit(),
        "กระบะ": NaiveUnit(),
        "ละเอียด": NaiveUnit(),
        "ปราสาท": NaiveUnit(),
        "ทาน": NaiveUnit(),
        "พายุ": NaiveUnit(),
        "หมุน": NaiveUnit(),
        "หิมะ": NaiveUnit(),
        "เค็ม": NaiveUnit(),
        "เปิด": NaiveUnit(),
        "ปลุก": NaiveUnit(),
        "นาฬิกา": NaiveUnit(),
        "กรวด": NaiveUnit(),
        "ตุ๊กตา": NaiveUnit(),
        "รส": NaiveUnit(),
        "สม": NaiveUnit(),
        "ชู": NaiveUnit(),
        "ไข่": NaiveUnit(),
        "จืด": NaiveUnit(),
        "ทุก": NaiveUnit(),
        "อื่น": NaiveUnit(),
        "บาง": NaiveUnit(),
        "จน": NaiveUnit(),
        "สัก": NaiveUnit(),
        "ขยิบ": NaiveUnit(),
        "ตาย": NaiveUnit(),
        "เล่น": NaiveUnit(),
        "เสีย": NaiveUnit(),
        "นั่ง": NaiveUnit(),
        "ดุ": NaiveUnit(),
        "วาย": NaiveUnit(),
        "พิษ": NaiveUnit(),
        "แว่น": NaiveUnit(),
        "ขยาย": NaiveUnit(),
        "กล้อง": NaiveUnit(),
        "ข่าว": NaiveUnit(),
        "ฝัน": NaiveUnit(),
        "เที่ยว": NaiveUnit(),
    }


def get_naive_compounds():
    return [
        NaiveCompound(
            english="cameraman, photographer",
            word_1="ตา",
            word_2="กล้อง",
        ),
        NaiveCompound(
            english="microscope",
            word_1="กล้อง",
            word_2="ขยาย",
        ),
        NaiveCompound(
            english="to zoom in",
            word_1="ขยาย",
            word_2="เข้า",
        ),
        NaiveCompound(
            english="magnify",
            word_1="ขยาย",
            word_2="ใหญ่",
        ),
        NaiveCompound(
            english="expanding",
            word_1="การ",
            word_2="ขยาย",
        ),
        NaiveCompound(
            english="magnifying glass",
            word_1="แว่น",
            word_2="ขยาย",
        ),
        NaiveCompound(
            english="dark glasses",
            word_1="แว่น",
            word_2="ดำ",
        ),
        NaiveCompound(
            english="eyeball, eye",
            word_1="ลูก",
            word_2="ตา",
        ),
        NaiveCompound(
            english="glasses",
            word_1="แว่น",
            word_2="ตา",
        ),
        NaiveCompound(
            english="tears",
            word_1="น้ำ",
            word_2="ตา",
        ),
        NaiveCompound(
            english="to have malice, wicked intentions",
            word_1="คิด",
            word_2="ร้าย",
        ),
        NaiveCompound(
            english="toxic",
            word_1="พิษ",
            word_2="ร้าย",
        ),
        NaiveCompound(
            english="devilish, evil, villain",
            word_1="วาย",
            word_2="ร้าย",
        ),
        NaiveCompound(
            english="fierce animal, wild animal",
            word_1="สัตว์",
            word_2="ร้าย",
        ),
        NaiveCompound(
            english="to be savage, ferocious, wild",
            word_1="ดุ",
            word_2="ร้าย",
        ),
        NaiveCompound(
            english="bad news",
            word_1="ข่าว",
            word_2="ร้าย",
        ),
        NaiveCompound(
            english="to be cruel, wicked, heartless",
            word_1="ใจ",
            word_2="ร้าย",
        ),
        NaiveCompound(
            english="to have a nightmare",
            word_1="ฝัน",
            word_2="ร้าย",
        ),
        NaiveCompound(
            english="harmful effect",
            word_1="ผล",
            word_2="ร้าย",
        ),
        NaiveCompound(
            english="enemy, bad guy",
            word_1="ตัว",
            word_2="ร้าย",
        ),
        NaiveCompound(
            english="to loaf, stroll, saunter",
            word_1="เที่ยว",
            word_2="เล่น",
        ),
        NaiveCompound(
            english="to be playful, mischievous, frisky",
            word_1="ขี้",
            word_2="เล่น",
        ),
        NaiveCompound(
            english="to joke, to kid",
            word_1="พูด",
            word_2="เล่น",
        ),
        NaiveCompound(
            english="nickname",
            word_1="ชื่อ",
            word_2="เล่น",
        ),
        NaiveCompound(
            english="to sit leisurely",
            word_1="นั่ง",
            word_2="เล่น",
        ),
        NaiveCompound(
            english="plaything",
            word_1="เครื่อง",
            word_2="เล่น",
        ),
        NaiveCompound(
            english="to stroll, take a walk",
            word_1="เดิน",
            word_2="เล่น",
        ),
        NaiveCompound(
            english="player",
            word_1="ผู้",
            word_2="เล่น",
        ),
        NaiveCompound(
            english="toy, plaything",
            word_1="ของ",
            word_2="เล่น",
        ),
        NaiveCompound(
            english="to play in the water",
            word_1="เล่น",
            word_2="น้ำ",
        ),
        NaiveCompound(
            english="the dead",
            word_1="คน",
            word_2="ตาย",
        ),
        NaiveCompound(
            english="driver, chauffeur",
            word_1="คน",
            word_2="ขับ",
        ),
        NaiveCompound(
            english="just one person",
            word_1="สัก",
            word_2="คน",
        ),
        NaiveCompound(
            english="employee, worker",
            word_1="คน",
            word_2="งาน",
        ),
        NaiveCompound(
            english="new one, new person",
            word_1="คน",
            word_2="ใหม่",
        ),
        NaiveCompound(
            english="poor people",
            word_1="คน",
            word_2="จน",
        ),
        NaiveCompound(
            english="criminal, culprit, offender",
            word_1="คน",
            word_2="ร้าย",
        ),
        NaiveCompound(
            english="alone, by oneself / one person",
            word_1="คน",
            word_2="เดียว",
        ),
        NaiveCompound(
            english="somebody",
            word_1="บาง",
            word_2="คน",
        ),
        NaiveCompound(
            english="someone else, others",
            word_1="คน",
            word_2="อื่น",
        ),
        NaiveCompound(
            english="Thai, thai people",
            word_1="คน",
            word_2="ไทย",
        ),
        NaiveCompound(
            english="everyone",
            word_1="ทุก",
            word_2="คน",
        ),
        NaiveCompound(
            english="flavorless, insipid, tasteless",
            word_1="รส",
            word_2="จืด",
        ),
        NaiveCompound(
            english="to blink, wink, twinkle",
            word_1="ขยิบ",
            word_2="ตา",
        ),
        NaiveCompound(
            english="to glance, glimpse",
            word_1="เล่น",
            word_2="ตา",
        ),
        NaiveCompound(
            english="blind",
            word_1="ตา",
            word_2="เสีย",
        ),
        NaiveCompound(
            english="to emit, give out an odor",
            word_1="ชู",
            word_2="กลิ่น",
        ),
        NaiveCompound(
            english="to raise one's hand",
            word_1="ชู",
            word_2="มือ",
        ),
        NaiveCompound(
            english="to encourage, inspire, hearten",
            word_1="ชู",
            word_2="ใจ",
        ),
        NaiveCompound(
            english="flavor, seasoning powder",
            word_1="ชู",
            word_2="รส",
        ),
        NaiveCompound(
            english="to marry, get married",
            word_1="สม",
            word_2="รส",
        ),
        NaiveCompound(
            english="flavor, taste, savor",
            word_1="รส",
            word_2="ชาติ",
        ),
        NaiveCompound(
            english="salted fish",
            word_1="ปลา",
            word_2="เค็ม",
        ),
        NaiveCompound(
            english="salted egg",
            word_1="ไข่",
            word_2="เค็ม",
        ),
        NaiveCompound(
            english="salty",
            word_1="รส",
            word_2="เค็ม",
        ),
        NaiveCompound(
            english="saltiness / stinginess",
            word_1="ความ",
            word_2="เค็ม",
        ),
        NaiveCompound(
            english="saltwater, sea water",
            word_1="น้ำ",
            word_2="เค็ม",
        ),
        NaiveCompound(
            english="snowman",
            word_1="ตุ๊กตา",
            word_2="หิมะ",
        ),
        NaiveCompound(
            english="pebble",
            word_1="กรวด",
            word_2="กลาง",
        ),
        NaiveCompound(
            english="to pour water, pour ceremonial water",
            word_1="กรวด",
            word_2="น้ำ",
        ),
        NaiveCompound(
            english="alarm clock",
            word_1="นาฬิกา",
            word_2="ปลุก",
        ),
        NaiveCompound(
            english="clock tower",
            word_1="หอ",
            word_2="นาฬิกา",
        ),
        NaiveCompound(
            english="mound, pile, heap",
            word_1="เนิน",
            word_2="ดิน",
        ),
        NaiveCompound(
            english="to open one's eyes wide",
            word_1="เปิด",
            word_2="ตา",
        ),
        NaiveCompound(
            english="alcaline soil, basic soil",
            word_1="ดิน",
            word_2="เค็ม",
        ),
        NaiveCompound(
            english="sandglass, hourglass, egg timer",
            word_1="นาฬิกา",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="pebble, grit, gravel",
            word_1="กรวด",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="snow storm",
            word_1="พายุ",
            word_2="หิมะ",
        ),
        NaiveCompound(
            english="cyclone",
            word_1="พายุ",
            word_2="หมุน",
        ),
        NaiveCompound(
            english="storm, tempest, hurricane",
            word_1="ลม",
            word_2="พายุ",
        ),
        NaiveCompound(
            english="rainstorm",
            word_1="พายุ",
            word_2="ฝน",
        ),
        NaiveCompound(
            english="sandstorm",
            word_1="พายุ",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="black sand",
            word_1="ทราย",
            word_2="ดำ",
        ),
        NaiveCompound(
            english="sand, sand floor",
            word_1="พื้น",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="fastidious person, punctilious person",
            word_1="คน",
            word_2="ละเอียด",
        ),
        NaiveCompound(
            english="to know the secret of",
            word_1="รู้",
            word_2="ละเอียด",
        ),
        NaiveCompound(
            english="sensitive, touchy, delicate",
            word_1="ละเอียด",
            word_2="อ่อน",
        ),
        NaiveCompound(
            english="fine sand",
            word_1="ทราย",
            word_2="ละเอียด",
        ),
        NaiveCompound(
            english="sandbox",
            word_1="กระบะ",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="sand castle",
            word_1="ปราสาท",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="sand dune",
            word_1="เนิน",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="grain of sand",
            word_1="เม็ด",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="sand paper, abrasive paper",
            word_1="กระดาษ",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="sandy soil",
            word_1="ดิน",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="sandstone",
            word_1="หิน",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="white sand",
            word_1="ทราย",
            word_2="ขาว",
        ),
        NaiveCompound(
            english="desert",
            word_1="ทะเล",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="sandy beach",
            word_1="หาด",
            word_2="ทราย",
        ),
        NaiveCompound(
            english="beach",
            word_1="ชาย",
            word_2="หาด",
        ),
        NaiveCompound(
            english="seaside, seashore",
            word_1="ชาย",
            word_2="ทะเล",
        ),
        NaiveCompound(
            english="riverside, waterside",
            word_1="ชาย",
            word_2="น้ำ",
        ),
        NaiveCompound(
            english="feast, banquet",
            word_1="ทาน",
            word_2="เลี้ยง",
        ),
        NaiveCompound(
            english="model",
            word_1="ตัว",
            word_2="แบบ",
        ),
        NaiveCompound(
            english="easily, simply",
            word_1="แบบ",
            word_2="ง่าย",
        ),
        NaiveCompound(
            english="any way, whichever way",
            word_1="แบบ",
            word_2="ใด",
        ),
        NaiveCompound(
            english="uniform",
            word_1="เครื่อง",
            word_2="แบบ",
        ),
        NaiveCompound(
            english="old-style, retro",
            word_1="แบบ",
            word_2="เดิม",
        ),
        NaiveCompound(
            english="model, mannequin",
            word_1="นาง",
            word_2="แบบ",
        ),
        NaiveCompound(
            english="Thai style",
            word_1="แบบ",
            word_2="ไทย",
        ),
        NaiveCompound(
            english="new, latest style",
            word_1="แบบ",
            word_2="ใหม่",
        ),
        NaiveCompound(
            english="like that, that way",
            word_1="แบบ",
            word_2="นั้น",
        ),
        NaiveCompound(
            english="design",
            word_1="ออก",
            word_2="แบบ",
        ),
        NaiveCompound(
            english="format",
            word_1="รูป",
            word_2="แบบ",
        ),
        NaiveCompound(
            english="like this, this way",
            word_1="แบบ",
            word_2="นี้",
        ),
        NaiveCompound(
            english="to glance, glimpse",
            word_1="ชาย",
            word_2="ตา",
        ),
        NaiveCompound(
            english="young man",
            word_1="ชาย",
            word_2="รุ่น",
        ),
        NaiveCompound(
            english="to have a lover, commit adultery",
            word_1="มี",
            word_2="ชู้",
        ),
        NaiveCompound(
            english="to have an affair, commit adultery",
            word_1="เป็น",
            word_2="ชู้",
        ),
        NaiveCompound(
            english="to be unfaithful, flirtatious",
            word_1="เจ้า",
            word_2="ชู้",
        ),
        NaiveCompound(
            english="adulterer",
            word_1="ชาย",
            word_2="ชู้",
        ),
        NaiveCompound(
            english="unmarried woman",
            word_1="หญิง",
            word_2="โสด",
        ),
        NaiveCompound(
            english="being single",
            word_1="ความ",
            word_2="โสด",
        ),
        NaiveCompound(
            english="unmarried woman, single woman",
            word_1="สาว",
            word_2="โสด",
        ),
        NaiveCompound(
            english="single person, bachelor, unmarried person",
            word_1="คน",
            word_2="โสด",
        ),
        NaiveCompound(
            english="bachelor, single man",
            word_1="ชาย",
            word_2="โสด",
        ),
        NaiveCompound(
            english="able-bodied man, fully grown man",
            word_1="ชาย",
            word_2="ฉกรรจ์",
        ),
        NaiveCompound(
            english="next generation, young generation",
            word_1="รุ่น",
            word_2="หลาน",
        ),
        NaiveCompound(
            english="lineage, descendant, pedigree",
            word_1="ลูก",
            word_2="หลาน",
        ),
        NaiveCompound(
            english="nephew, grandson",
            word_1="หลาน",
            word_2="ชาย",
        ),
        NaiveCompound(
            english="Mr",
            word_1="คุณ",
            word_2="ชาย",
        ),
        NaiveCompound(
            english="to modify, adapt, alter",
            word_1="เปลี่ยน",
            word_2="แบบ",
        ),
        NaiveCompound(
            english="to change jobs",
            word_1="เปลี่ยน",
            word_2="งาน",
        ),
        NaiveCompound(
            english="to change hands, make over",
            word_1="เปลี่ยน",
            word_2="มือ",
        ),
        NaiveCompound(
            english="to switch, alter",
            word_1="สับ",
            word_2="เปลี่ยน",
        ),
        NaiveCompound(
            english="to change clothes",
            word_1="เปลี่ยน",
            word_2="เสื้อ",
        ),
        NaiveCompound(
            english="to move, transfer",
            word_1="เปลี่ยน",
            word_2="ที่",
        ),
        NaiveCompound(
            english="to have a changed apparence, become different",
            word_1="เปลี่ยน",
            word_2="รูป",
        ),
        NaiveCompound(
            english="to alternate, take turns",
            word_1="เปลี่ยน",
            word_2="กัน",
        ),
        NaiveCompound(
            english="to change, change color",
            word_1="เปลี่ยน",
            word_2="สี",
        ),
        NaiveCompound(
            english="to change into, turn into",
            word_1="เปลี่ยน",
            word_2="ไป",
        ),
        NaiveCompound(
            english="change, modification",
            word_1="การ",
            word_2="เปลี่ยน",
        ),
        NaiveCompound(
            english="to change, alter, modify",
            word_1="เปลี่ยน",
            word_2="แปลง",
        ),
        NaiveCompound(
            english="principle, philosophy",
            word_1="อุดม",
            word_2="การ",
        ),
        NaiveCompound(
            english="fertility, abundance, plentiful",
            word_1="ความ",
            word_2="อุดม",
        ),
        NaiveCompound(
            english="ideology",
            word_1="อุดม",
            word_2="การณ์",
        ),
        NaiveCompound(
            english="pre-elementary school, kindergarten",
            word_1="เตรียม",
            word_2="ประถม",
        ),
        NaiveCompound(
            english="primary school pupil",
            word_1="เด็ก",
            word_2="ประถม",
        ),
        NaiveCompound(
            english="status",
            word_1="สถาน",
            word_2="ภาพ",
        ),
        NaiveCompound(
            english="higher education",
            word_1="อุดม",
            word_2="ศึกษา",
        ),
        NaiveCompound(
            english="case study",
            word_1="กรณี",
            word_2="ศึกษา",
        ),
        NaiveCompound(
            english="elementary education, primary education",
            word_1="ประถม",
            word_2="ศึกษา",
        ),
        NaiveCompound(
            english="to further study, continue to study",
            word_1="ศึกษา",
            word_2="ต่อ",
        ),
        NaiveCompound(
            english="school, academy, college",
            word_1="สถาน",
            word_2="ศึกษา",
        ),
        NaiveCompound(
            english="student, learner",
            word_1="นัก",
            word_2="ศึกษา",
        ),
        NaiveCompound(
            english="education",
            word_1="การ",
            word_2="ศึกษา",
        ),
        NaiveCompound(
            english="son",
            word_1="บุตร",
            word_2="ชาย",
        ),
        NaiveCompound(
            english="sex education",
            word_1="เพศ",
            word_2="ศึกษา",
        ),
        NaiveCompound(
            english="to be of the same sex / to have sex",
            word_1="ร่วม",
            word_2="เพศ",
        ),
        NaiveCompound(
            english="of the opposite sex",
            word_1="ต่าง",
            word_2="เพศ",
        ),
        NaiveCompound(
            english="to change sex",
            word_1="เปลี่ยน",
            word_2="เพศ",
        ),
        NaiveCompound(
            english="to leave the monkhood",
            word_1="ลา",
            word_2="เพศ",
        ),
        NaiveCompound(
            english="feminine, female gender",
            word_1="เพศ",
            word_2="หญิง",
        ),
        NaiveCompound(
            english="masculine, male gender",
            word_1="เพศ",
            word_2="ชาย",
        ),
        NaiveCompound(
            english="to be a man, be masculine, be male",
            word_1="เป็น",
            word_2="ชาย",
        ),
        NaiveCompound(
            english="boy",
            word_1="เด็ก",
            word_2="ชาย",
        ),
        NaiveCompound(
            english="baby-sitter",
            word_1="คน",
            word_2="เลี้ยง",
        ),
        NaiveCompound(
            english="uncle",
            word_1="น้า",
            word_2="ชาย",
        ),
        NaiveCompound(
            english="mosquito net",
            word_1="มุ้ง",
            word_2="ครอบ",
        ),
        NaiveCompound(
            english="covering",
            word_1="การ",
            word_2="ครอบ",
        ),
        NaiveCompound(
            english="dominate, overpower, reign",
            word_1="ครอบ",
            word_2="งำ",
        ),
        NaiveCompound(
            english="aunt",
            word_1="น้า",
            word_2="สะใภ้",
        ),
        NaiveCompound(
            english="daughter-in-law",
            word_1="ลูก",
            word_2="สะใภ้",
        ),
        NaiveCompound(
            english="daughter-in-law",
            word_1="ลูก",
            word_2="สะใภ้",
        ),
        NaiveCompound(
            english="sister-in-law",
            word_1="พี่",
            word_2="สะใภ้",
        ),
        NaiveCompound(
            english="eldest sister / eldest brother",
            word_1="พี่",
            word_2="ใหญ่",
        ),
        NaiveCompound(
            english="senior",
            word_1="รุ่น",
            word_2="พี่",
        ),
        NaiveCompound(
            english="sister (when older)",
            word_1="พี่",
            word_2="สาว",
        ),
        NaiveCompound(
            english="brother (when older)",
            word_1="พี่",
            word_2="ชาย",
        ),
        NaiveCompound(
            english="brother / sister",
            word_1="พี่",
            word_2="น้อง",
        ),
        NaiveCompound(
            english="nanny",
            word_1="พี่",
            word_2="เลี้ยง",
        ),
        NaiveCompound(
            english="pet, domestic animal",
            word_1="สัตว์",
            word_2="เลี้ยง",
        ),
        NaiveCompound(
            english="to entertain guests, to have a party",
            word_1="เลี้ยง",
            word_2="แขก",
        ),
        NaiveCompound(
            english="to give someone a treat / to support, raise",
            word_1="เลี้ยง",
            word_2="ดู",
        ),
        NaiveCompound(
            english="wealthy man",
            word_1="พ่อ",
            word_2="เลี้ยง",
        ),
        NaiveCompound(
            english="wizard",
            word_1="พ่อ",
            word_2="มด",
        ),
        NaiveCompound(
            english="kitchen garden",
            word_1="สวน",
            word_2="ครัว",
        ),
        NaiveCompound(
            english="cook, chef",
            word_1="พ่อ",
            word_2="ครัว",
        ),
        NaiveCompound(
            english="when, as, while",
            word_1="ขณะ",
            word_2="เมื่อ",
        ),
        NaiveCompound(
            english="Spanish language",
            word_1="ภาษา",
            word_2="สเปน",
        ),
        NaiveCompound(
            english="Korean language",
            word_1="ภาษา",
            word_2="เกาหลี",
        ),
        NaiveCompound(
            english="kitchen",
            word_1="ห้อง",
            word_2="ครัว",
        ),
        NaiveCompound(
            english="library",
            word_1="ห้อง",
            word_2="สมุด",
        ),
        NaiveCompound(
            english="bedroom",
            word_1="ห้อง",
            word_2="นอน",
        ),
        NaiveCompound(
            english="classroom",
            word_1="ห้อง",
            word_2="เรียน",
        ),
        NaiveCompound(
            english="native land, habitat, homeland",
            word_1="ถิ่น",
            word_2="เกิด",
        ),
        NaiveCompound(
            english="area, section, locality",
            word_1="ถิ่น",
            word_2="ที่",
        ),
        NaiveCompound(
            english="while, meanwhile",
            word_1="ใน",
            word_2="ขณะ",
        ),
        NaiveCompound(
            english="in one's heart, in one's mind",
            word_1="ใน",
            word_2="ใจ",
        ),
        NaiveCompound(
            english="dialect, regional speech, localism",
            word_1="ภาษา",
            word_2="ถิ่น",
        ),
        NaiveCompound(
            english="German language",
            word_1="ภาษา",
            word_2="เยอรมัน",
        ),
        NaiveCompound(
            english="French language",
            word_1="ภาษา",
            word_2="ฝรั่งเศส",
        ),
        NaiveCompound(
            english="meditation / way in",
            word_1="ทาง",
            word_2="ใน",
        ),
        NaiveCompound(
            english="area, place, lot",
            word_1="ที่",
            word_2="ทาง",
        ),
        NaiveCompound(
            english="entrance",
            word_1="ทาง",
            word_2="เข้า",
        ),
        NaiveCompound(
            english="travel, journey",
            word_1="เดิน",
            word_2="ทาง",
        ),
        NaiveCompound(
            english="route, way, course",
            word_1="เส้น",
            word_2="ทาง",
        ),
        NaiveCompound(
            english="to scold, reprimand, censure",
            word_1="ด่า",
            word_2="ว่า",
        ),
        NaiveCompound(
            english="to insult back",
            word_1="ด่า",
            word_2="ตอบ",
        ),
        NaiveCompound(
            english="linguistically",
            word_1="ทาง",
            word_2="ภาษา",
        ),
        NaiveCompound(
            english="to answer, to reply",
            word_1="ตอบ",
            word_2="กลับ",
        ),
        NaiveCompound(
            english="answer, reply",
            word_1="คำ",
            word_2="ตอบ",
        ),
        NaiveCompound(
            english="to counter-attack",
            word_1="รบ",
            word_2="ตอบ",
        ),
        NaiveCompound(
            english="to wash the dishes",
            word_1="ล้าง",
            word_2="จาน",
        ),
        NaiveCompound(
            english="to declare a truce",
            word_1="พัก",
            word_2="รบ",
        ),
        NaiveCompound(
            english="disturbing, bothering",
            word_1="การ",
            word_2="รบ",
        ),
        NaiveCompound(
            english="combatant, fighter, man-at-arms",
            word_1="นัก",
            word_2="รบ",
        ),
        NaiveCompound(
            english="flying saucer",
            word_1="จาน",
            word_2="บิน",
        ),
        NaiveCompound(
            english="to land",
            word_1="บิน",
            word_2="ลง",
        ),
        NaiveCompound(
            english="to take off, to fly up",
            word_1="บิน",
            word_2="ขึ้น",
        ),
        NaiveCompound(
            english="pilot",
            word_1="นัก",
            word_2="บิน",
        ),
        NaiveCompound(
            english="flying",
            word_1="การ",
            word_2="บิน",
        ),
        NaiveCompound(
            english="aircraft",
            word_1="เครื่อง",
            word_2="บิน",
        ),
        NaiveCompound(
            english="hot tea",
            word_1="ชา",
            word_2="ร้อน",
        ),
        NaiveCompound(
            english="tea",
            word_1="น้ำ",
            word_2="ชา",
        ),
        NaiveCompound(
            english="tea leaf",
            word_1="ใบ",
            word_2="ชา",
        ),
        NaiveCompound(
            english="battlefield",
            word_1="สนาม",
            word_2="รบ",
        ),
        NaiveCompound(
            english="airport",
            word_1="สนาม",
            word_2="บิน",
        ),
        NaiveCompound(
            english="sea breeze",
            word_1="ลม",
            word_2="ทะเล",
        ),
        NaiveCompound(
            english="to faint, to have a stroke",
            word_1="เป็น",
            word_2="ลม",
        ),
        NaiveCompound(
            english="master thief",
            word_1="มือ",
            word_2="ดี",
        ),
        NaiveCompound(
            english="iced tea",
            word_1="ชา",
            word_2="เย็น",
        ),
        NaiveCompound(
            english="cold wind, cold air",
            word_1="ลม",
            word_2="เย็น",
        ),
        NaiveCompound(
            english="to be cold",
            word_1="หนาว",
            word_2="เย็น",
        ),
        NaiveCompound(
            english="cold water",
            word_1="น้ำ",
            word_2="เย็น",
        ),
        NaiveCompound(
            english="evening, twilight, dusk",
            word_1="เวลา",
            word_2="เย็น",
        ),
        NaiveCompound(
            english="future life, life to come",
            word_1="ชาติ",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="next time",
            word_1="คราว",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="to boast",
            word_1="ราคา",
            word_2="คุย",
        ),
        NaiveCompound(
            english="to bargain",
            word_1="ต่อ",
            word_2="ราคา",
        ),
        NaiveCompound(
            english="sarong",
            word_1="ผ้า",
            word_2="ถุง",
        ),
        NaiveCompound(
            english="cool shade",
            word_1="ร่ม",
            word_2="เย็น",
        ),
        NaiveCompound(
            english="foremost",
            word_1="หน้า",
            word_2="สุด",
        ),
        NaiveCompound(
            english="wholeheartedly",
            word_1="สุด",
            word_2="ใจ",
        ),
        NaiveCompound(
            english="last, final",
            word_1="หลัง",
            word_2="สุด",
        ),
        NaiveCompound(
            english="max",
            word_1="มาก",
            word_2="สุด",
        ),
        NaiveCompound(
            english="to be great, excellent",
            word_1="สุด",
            word_2="ยอด",
        ),
        NaiveCompound(
            english="guardian, protector",
            word_1="ร่ม",
            word_2="เกล้า",
        ),
        NaiveCompound(
            english="tiara",
            word_1="รัด",
            word_2="เกล้า",
        ),
        NaiveCompound(
            english="to be busy / tied up",
            word_1="รัด",
            word_2="ตัว",
        ),
        NaiveCompound(
            english="extreme",
            word_1="ปลาย",
            word_2="สุด",
        ),
        NaiveCompound(
            english="finger tip",
            word_1="ปลาย",
            word_2="นิ้ว",
        ),
        NaiveCompound(
            english="rubber band",
            word_1="ยาง",
            word_2="รัด",
        ),
        NaiveCompound(
            english="latex",
            word_1="น้ำ",
            word_2="ยาง",
        ),
        NaiveCompound(
            english="rubber plantation",
            word_1="สวน",
            word_2="ยาง",
        ),
        NaiveCompound(
            english="toes",
            word_1="ปลาย",
            word_2="เท้า",
        ),
        NaiveCompound(
            english="ankle",
            word_1="ข้อ",
            word_2="เท้า",
        ),
        NaiveCompound(
            english="sole",
            word_1="ฝ่า",
            word_2="เท้า",
        ),
        NaiveCompound(
            english="condom",
            word_1="ถุง",
            word_2="ยาง",
        ),
        NaiveCompound(
            english="plastic bag",
            word_1="ถุง",
            word_2="พลาสติก",
        ),
        NaiveCompound(
            english="sock",
            word_1="ถุง",
            word_2="เท้า",
        ),
        NaiveCompound(
            english="glove",
            word_1="ถุง",
            word_2="สือ",
        ),
        NaiveCompound(
            english="letter, character",
            word_1="ลาย",
            word_2="สือ",
        ),
        NaiveCompound(
            english="handwriting",
            word_1="ลาย",
            word_2="มือ",
        ),
        NaiveCompound(
            english="to move from side to side, to oscillate",
            word_1="ดีด",
            word_2="ตัว",
        ),
        NaiveCompound(
            english="to snap one's fingers",
            word_1="ดีด",
            word_2="นิ้ว",
        ),
        NaiveCompound(
            english="left-hand, left side",
            word_1="ซ้าย",
            word_2="มือ",
        ),
        NaiveCompound(
            english="finger",
            word_1="นิ้ว",
            word_2="มือ",
        ),
        NaiveCompound(
            english="palm, sole",
            word_1="ฝ่า",
            word_2="มือ",
        ),
        NaiveCompound(
            english="wrist",
            word_1="ข้อ",
            word_2="มือ",
        ),
        NaiveCompound(
            english="right-hand, right side",
            word_1="ขวา",
            word_2="มือ",
        ),
        NaiveCompound(
            english="to hold hands",
            word_1="จับ",
            word_2="มือ",
        ),
        NaiveCompound(
            english="novice, beginner",
            word_1="มือ",
            word_2="ใหม่",
        ),
        NaiveCompound(
            english="second hand",
            word_1="มือ",
            word_2="สอง",
        ),
        NaiveCompound(
            english="mobile phone",
            word_1="มือ",
            word_2="ถือ",
        ),
        NaiveCompound(
            english="tool, apparatus",
            word_1="เครื่อง",
            word_2="มือ",
        ),
        NaiveCompound(
            english="science",
            word_1="วิทยา",
            word_2="ศาสตร์",
        ),
        NaiveCompound(
            english="trigger (of a weapon)",
            word_1="ไก",
            word_2="ปืน",
        ),
        NaiveCompound(
            english="gunpowder",
            word_1="ดิน",
            word_2="ปืน",
        ),
        NaiveCompound(
            english="hitman, hired killer",
            word_1="มือ",
            word_2="ปืน",
        ),
        NaiveCompound(
            english="machine gun",
            word_1="ปืน",
            word_2="กล",
        ),
        NaiveCompound(
            english="roasted pork",
            word_1="หมู",
            word_2="ย่าง",
        ),
        NaiveCompound(
            english="roasted red pork",
            word_1="หมู",
            word_2="แดง",
        ),
        NaiveCompound(
            english="year of the pig",
            word_1="ปี",
            word_2="หมู",
        ),
        NaiveCompound(
            english="ham",
            word_1="หมู",
            word_2="แฮม",
        ),
        NaiveCompound(
            english="wild boar",
            word_1="หมู",
            word_2="ป่า",
        ),
        NaiveCompound(
            english="minced pork",
            word_1="หมู",
            word_2="สับ",
        ),
        NaiveCompound(
            english="to pull the trigger",
            word_1="สับ",
            word_2="ไก",
        ),
        NaiveCompound(
            english="mechanism, machinery, device",
            word_1="กล",
            word_2="ไก",
        ),
        NaiveCompound(
            english="mechanics, mechanical science",
            word_1="กล",
            word_2="ศาสตร์",
        ),
        NaiveCompound(
            english="humanities",
            word_1="มนุษย์",
            word_2="ศาสตร์",
        ),
        NaiveCompound(
            english="linguistics",
            word_1="ภาษา",
            word_2="ศาสตร์",
        ),
        NaiveCompound(
            english="Burmese language",
            word_1="ภาษา",
            word_2="พม่า",
        ),
        NaiveCompound(
            english="interlingua, common tongue",
            word_1="ภาษา",
            word_2="กลาง",
        ),
        NaiveCompound(
            english="mother tongue",
            word_1="ภาษา",
            word_2="แม่",
        ),
        NaiveCompound(
            english="Malay language",
            word_1="ภาษา",
            word_2="มลายู",
        ),
        NaiveCompound(
            english="Sanskrit",
            word_1="ภาษา",
            word_2="สันสกฤต",
        ),
        NaiveCompound(
            english="according to",
            word_1="ตาม",
            word_2="ภาษา",
        ),
        NaiveCompound(
            english="Pali",
            word_1="ภาษา",
            word_2="บาลี",
        ),
        NaiveCompound(
            english="written language",
            word_1="ภาษา",
            word_2="เขียน",
        ),
        NaiveCompound(
            english="colloquialism",
            word_1="ภาษา",
            word_2="พูด",
        ),
        NaiveCompound(
            english="Japanese language",
            word_1="ภาษา",
            word_2="ญี่ปุ่น",
        ),
        NaiveCompound(
            english="Chinese language",
            word_1="ภาษา",
            word_2="จีน",
        ),
        NaiveCompound(
            english="Thai language",
            word_1="ภาษา",
            word_2="ไทย",
        ),
        NaiveCompound(
            english="English language",
            word_1="ภาษา",
            word_2="อังกฤษ",
        ),
        NaiveCompound(
            english="market price",
            word_1="ราคา",
            word_2="ตลาด",
        ),
        NaiveCompound(
            english="to be of good price, to fetch a good price",
            word_1="ได้",
            word_2="ราคา",
        ),
        NaiveCompound(
            english="selling price",
            word_1="ราคา",
            word_2="ขาย",
        ),
        NaiveCompound(
            english="to raise the price",
            word_1="ขึ้น",
            word_2="ราคา",
        ),
        NaiveCompound(
            english="to discount, to lower the price",
            word_1="ลด",
            word_2="ราคา",
        ),
        NaiveCompound(
            english="to be valuable, expensive",
            word_1="มี",
            word_2="ราคา",
        ),
        NaiveCompound(
            english="to be cheap",
            word_1="ราคา",
            word_2="ถูก",
        ),
        NaiveCompound(
            english="to be bragful",
            word_1="ขี้",
            word_2="คุย",
        ),
        NaiveCompound(
            english="to brag, boast",
            word_1="ราคา",
            word_2="คุย",
        ),
        NaiveCompound(
            english="chatting / bragging",
            word_1="การ",
            word_2="คุย",
        ),
        NaiveCompound(
            english="conversation room, chat room",
            word_1="ห้อง",
            word_2="คุย",
        ),
        NaiveCompound(
            english="to chat, talk, converse",
            word_1="พูด",
            word_2="คุย",
        ),
        NaiveCompound(
            english="interlocutor, conversationalist, talker",
            word_1="เพื่อน",
            word_2="คุย",
        ),
        NaiveCompound(
            english="true friend",
            word_1="เพื่อน",
            word_2="แท้",
        ),
        NaiveCompound(
            english="frogman (trained scuba diver)",
            word_1="มนุษย์",
            word_2="กบ",
        ),
        NaiveCompound(
            english="fellowman",
            word_1="เพื่อน",
            word_2="มนุษย์",
        ),
        NaiveCompound(
            english="human language",
            word_1="ภาษา",
            word_2="มนุษย์",
        ),
        NaiveCompound(
            english="mankind",
            word_1="มวล",
            word_2="มนุษย์",
        ),
        NaiveCompound(
            english="homonym, homophone, homograph",
            word_1="คำ",
            word_2="พ้อง",
        ),
        NaiveCompound(
            english="to agree, to see the same way as",
            word_1="เห็น",
            word_2="พ้อง",
        ),
        NaiveCompound(
            english="friends, relatives, companions",
            word_1="พวก",
            word_2="พ้อง",
        ),
        NaiveCompound(
            english="friends",
            word_1="เพื่อน",
            word_2="พ้อง",
        ),
        NaiveCompound(
            english="to be friends / to accompany someone",
            word_1="เป็น",
            word_2="เพื่อน",
        ),
        NaiveCompound(
            english="pain, ache",
            word_1="ความ",
            word_2="ปวด",
        ),
        NaiveCompound(
            english="to heartache",
            word_1="ปวด",
            word_2="ใจ",
        ),
        NaiveCompound(
            english="to have a backache",
            word_1="ปวด",
            word_2="หลัง",
        ),
        NaiveCompound(
            english="to have a stomachache",
            word_1="ปวด",
            word_2="ท้อง",
        ),
        NaiveCompound(
            english="pheasant",
            word_1="ไก่",
            word_2="ฟ้า",
        ),
        NaiveCompound(
            english="bus",
            word_1="ขับ",
            word_2="บัส",
        ),
        NaiveCompound(
            english="to drive",
            word_1="ขับ",
            word_2="รถ",
        ),
        NaiveCompound(
            english="chimney, smoke vent",
            word_1="ปล่อง",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="pile of merit",
            word_1="กอง",
            word_2="บุญ",
        ),
        NaiveCompound(
            english="bonfire, campfire",
            word_1="กอง",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="to have a headache",
            word_1="ปวด",
            word_2="หัว",
        ),
        NaiveCompound(
            english="boss, chief, leader",
            word_1="หัว",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="to laugh",
            word_1="หัว",
            word_2="เราะ",
        ),
        NaiveCompound(
            english="topic, subject",
            word_1="หัว",
            word_2="ข้อ",
        ),
        NaiveCompound(
            english="heart",
            word_1="หัว",
            word_2="ใจ",
        ),
        NaiveCompound(
            english="powder mixed with water to revive someone",
            word_1="ยา",
            word_2="หอม",
        ),
        NaiveCompound(
            english="onion",
            word_1="หัว",
            word_2="หอม",
        ),
        NaiveCompound(
            english="fragrance",
            word_1="ความ",
            word_2="หอม",
        ),
        NaiveCompound(
            english="perfume",
            word_1="น้ำ",
            word_2="หอม",
        ),
        NaiveCompound(
            english="to smell good",
            word_1="กลิ่น",
            word_2="หอม",
        ),
        NaiveCompound(
            english="to behead, decapitate",
            word_1="ตัด",
            word_2="หัว",
        ),
        NaiveCompound(
            english="eliminate",
            word_1="ตัด",
            word_2="ออก",
        ),
        NaiveCompound(
            english="to part with something, give up something (reluctantly)",
            word_1="ตัด",
            word_2="ใจ",
        ),
        NaiveCompound(
            english="rain cloud, nimbus",
            word_1="เมฆ",
            word_2="ฝน",
        ),
        NaiveCompound(
            english="banana",
            word_1="กล้วย",
            word_2="หอม",
        ),
        NaiveCompound(
            english="translating",
            word_1="การ",
            word_2="แปล",
        ),
        NaiveCompound(
            english="translator",
            word_1="ผู้",
            word_2="แปล",
        ),
        NaiveCompound(
            english="mushroom",
            word_1="ดอก",
            word_2="เห็ด",
        ),
        NaiveCompound(
            english="translation",
            word_1="คำ",
            word_2="แปล",
        ),
        NaiveCompound(
            english="rather, somewhat",
            word_1="ออก",
            word_2="จะ",
        ),
        NaiveCompound(
            english="gold flower / prostitute",
            word_1="ดอก",
            word_2="ทอง",
        ),
        NaiveCompound(
            english="petal, corolla",
            word_1="กลีบ",
            word_2="ดอก",
        ),
        NaiveCompound(
            english="flower",
            word_1="ดอก",
            word_2="ไม้",
        ),
        NaiveCompound(
            english="to bloom, produce flowers",
            word_1="ออก",
            word_2="ดอก",
        ),
        NaiveCompound(
            english="to sort out",
            word_1="คัด",
            word_2="ออก",
        ),
        NaiveCompound(
            english="to pay",
            word_1="ออก",
            word_2="เงิน",
        ),
        NaiveCompound(
            english="to remember, recall / to figure out a solution",
            word_1="คิด",
            word_2="ออก",
        ),
        NaiveCompound(
            english="to resign, quit, leave",
            word_1="ลา",
            word_2="ออก",
        ),
        NaiveCompound(
            english="to export, send abroad",
            word_1="ส่ง",
            word_2="ออก",
        ),
        NaiveCompound(
            english="request",
            word_1="คำ",
            word_2="ขอ",
        ),
        NaiveCompound(
            english="words, speech",
            word_1="คำ",
            word_2="พูด",
        ),
        NaiveCompound(
            english="question",
            word_1="คำ",
            word_2="ถาม",
        ),
        NaiveCompound(
            english="orchid",
            word_1="กล้วย",
            word_2="ไม้",
        ),
        NaiveCompound(
            english="to say, speak, talk",
            word_1="ออก",
            word_2="ปาก",
        ),
        NaiveCompound(
            english="estuary, mouth of a river",
            word_1="ปาก",
            word_2="น้ำ",
        ),
        NaiveCompound(
            english="root word",
            word_1="ราก",
            word_2="คำ",
        ),
        NaiveCompound(
            english="tooth root",
            word_1="ราก",
            word_2="ฟัน",
        ),
        NaiveCompound(
            english="to wear lipstick",
            word_1="ทา",
            word_2="ปาก",
        ),
        NaiveCompound(
            english="roots of hair",
            word_1="ราก",
            word_2="ผม",
        ),
        NaiveCompound(
            english="to paint",
            word_1="ทา",
            word_2="สี",
        ),
        NaiveCompound(
            english="to be orange",
            word_1="สี",
            word_2="ส้ม",
        ),
        NaiveCompound(
            english="to be golden (color)",
            word_1="สี",
            word_2="ทอง",
        ),
        NaiveCompound(
            english="to be red",
            word_1="สี",
            word_2="แดง",
        ),
        NaiveCompound(
            english="to be white",
            word_1="สี",
            word_2="ขาว",
        ),
        NaiveCompound(
            english="to have a halo",
            word_1="ทรง",
            word_2="กลด",
        ),
        NaiveCompound(
            english="topknot",
            word_1="ผม",
            word_2="จุก",
        ),
        NaiveCompound(
            english="hair color",
            word_1="สี",
            word_2="ผม",
        ),
        NaiveCompound(
            english="hairstyle, haircut",
            word_1="ทรง",
            word_2="ผม",
        ),
        NaiveCompound(
            english="to chop wood",
            word_1="ตัด",
            word_2="ไม้",
        ),
        NaiveCompound(
            english="to get a haircut, to cut hair",
            word_1="ตัด",
            word_2="ผม",
        ),
        NaiveCompound(
            english="to have surgery, to have an operation",
            word_1="ผ่า",
            word_2="ตัด",
        ),
        NaiveCompound(
            english="cutting off",
            word_1="การ",
            word_2="ตัด",
        ),
        NaiveCompound(
            english="art gallery",
            word_1="หอ",
            word_2="ศิลป์",
        ),
        NaiveCompound(
            english="monks room",
            word_1="หอ",
            word_2="พระ",
        ),
        NaiveCompound(
            english="to decide",
            word_1="ตัด",
            word_2="สิน",
        ),
        NaiveCompound(
            english="dormitory",
            word_1="หอ",
            word_2="พัก",
        ),
        NaiveCompound(
            english="recently",
            word_1="พัก",
            word_2="นี้",
        ),
        NaiveCompound(
            english="mob rule, majority power",
            word_1="กฎ",
            word_2="หมู่",
        ),
        NaiveCompound(
            english="to comply with the rules",
            word_1="ถูก",
            word_2="กฎ",
        ),
        NaiveCompound(
            english="to extinguish a fire",
            word_1="ดับ",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="forest fire",
            word_1="ไฟ",
            word_2="ป่า",
        ),
        NaiveCompound(
            english="train",
            word_1="รถ",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="spark",
            word_1="ลูก",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="to turn off the light",
            word_1="ปิด",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="red light",
            word_1="ไฟ",
            word_2="แดง",
        ),
        NaiveCompound(
            english="electricity",
            word_1="ไฟ",
            word_2="ฟ้า",
        ),
        NaiveCompound(
            english="to encompass",
            word_1="หมาย",
            word_2="รวม",
        ),
        NaiveCompound(
            english="to mean",
            word_1="หมาย",
            word_2="ถึง",
        ),
        NaiveCompound(
            english="law",
            word_1="กฎ",
            word_2="หมาย",
        ),
        NaiveCompound(
            english="center, hub",
            word_1="จุด",
            word_2="รวม",
        ),
        NaiveCompound(
            english="intersection point",
            word_1="จุด",
            word_2="ตัด",
        ),
        NaiveCompound(
            english="selling point",
            word_1="จุด",
            word_2="ขาย",
        ),
        NaiveCompound(
            english="strength, good point",
            word_1="จุด",
            word_2="แข็ง",
        ),
        NaiveCompound(
            english="end, end point",
            word_1="จุด",
            word_2="จบ",
        ),
        NaiveCompound(
            english="goal, aim, purpose",
            word_1="จุด",
            word_2="หมาย",
        ),
        NaiveCompound(
            english="ignite",
            word_1="จุด",
            word_2="ไฟ",
        ),
        NaiveCompound(
            english="aquarium",
            word_1="ตู้",
            word_2="ปลา",
        ),
        NaiveCompound(
            english="magma",
            word_1="หิน",
            word_2="หนืด",
        ),
        NaiveCompound(
            english="goldfish",
            word_1="ปลา",
            word_2="แดง",
        ),
        NaiveCompound(
            english="copper",
            word_1="ทอง",
            word_2="แดง",
        ),
        NaiveCompound(
            english="gold",
            word_1="ทอง",
            word_2="คำ",
        ),
        NaiveCompound(
            english="say goodbye, leave",
            word_1="ลา",
            word_2="ก่อน",
        ),
        NaiveCompound(
            english="wait and see, see what happens",
            word_1="ดู",
            word_2="ก่อน",
        ),
        NaiveCompound(
            english="last year",
            word_1="ปี",
            word_2="ก่อน",
        ),
        NaiveCompound(
            english="golden age",
            word_1="ยุค",
            word_2="ทอง",
        ),
        NaiveCompound(
            english="stalactite",
            word_1="หิน",
            word_2="ย้อย",
        ),
        NaiveCompound(
            english="new model",
            word_1="รุ่น",
            word_2="ใหม่",
        ),
        NaiveCompound(
            english="stone age",
            word_1="ยุค",
            word_2="หิน",
        ),
        NaiveCompound(
            english="tadpole",
            word_1="ลูก",
            word_2="อ๊อด",
        ),
        NaiveCompound(
            english="globe",
            word_1="ลูก",
            word_2="โลก",
        ),
        NaiveCompound(
            english="true love",
            word_1="รัก",
            word_2="แท้",
        ),
        NaiveCompound(
            english="to be diligent, persevering",
            word_1="รัก",
            word_2="ดี",
        ),
        NaiveCompound(
            english="valued friend, bosom friend, close friend",
            word_1="เพื่อน",
            word_2="รัก",
        ),
        NaiveCompound(
            english="to be extremely fond of, to love, to be bent on",
            word_1="ใจ",
            word_2="รัก",
        ),
        NaiveCompound(
            english="patriotic",
            word_1="รัก",
            word_2="ชาติ",
        ),
        NaiveCompound(
            english="lover, boyfriend, girlfriend",
            word_1="คู่",
            word_2="รัก",
        ),
        NaiveCompound(
            english="lover, darling",
            word_1="คน",
            word_2="รัก",
        ),
        NaiveCompound(
            english="cute, attractive, pretty",
            word_1="น่า",
            word_2="รัก",
        ),
        NaiveCompound(
            english="love",
            word_1="ความ",
            word_2="รัก",
        ),
        NaiveCompound(
            english="reason",
            word_1="เหตุ",
            word_2="ผล",
        ),
        NaiveCompound(
            english="sweetheart (talking to one's child)",
            word_1="ลูก",
            word_2="รัก",
        ),
        NaiveCompound(
            english="works / success, accomplishment, achievement",
            word_1="ผล",
            word_2="งาน",
        ),
        NaiveCompound(
            english="big project",
            word_1="งาน",
            word_2="ช้าง",
        ),
        NaiveCompound(
            english="elephant ivory tusk",
            word_1="งา",
            word_2="ช้าง",
        ),
        NaiveCompound(
            english="white (albino) elephant",
            word_1="ช้าง",
            word_2="เผือก",
        ),
        NaiveCompound(
            english="to diminish, lessen, reduce",
            word_1="อ่อน",
            word_2="ตัว",
        ),
        NaiveCompound(
            english="weakness",
            word_1="ความ",
            word_2="อ่อน",
        ),
        NaiveCompound(
            english="weak point",
            word_1="จุด",
            word_2="อ่อน",
        ),
        NaiveCompound(
            english="to be weak, feeble, tired",
            word_1="อ่อน",
            word_2="แอ",
        ),
        NaiveCompound(
            english="elephant calf",
            word_1="ลูก",
            word_2="ช้าง",
        ),
        NaiveCompound(
            english="mosquito larva",
            word_1="ลูก",
            word_2="น้ำ",
        ),
        NaiveCompound(
            english="baby, infant",
            word_1="ลูก",
            word_2="อ่อน",
        ),
        NaiveCompound(
            english="chick, baby chicken",
            word_1="ลูก",
            word_2="ไก่",
        ),
        NaiveCompound(
            english="sponge",
            word_1="ฟอง",
            word_2="น้ำ",
        ),
        NaiveCompound(
            english="to bubble, to foam",
            word_1="เป็น",
            word_2="ฟอง",
        ),
        NaiveCompound(
            english="future",
            word_1="ภาย",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="to precede, to lead",
            word_1="นำ",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="next year, coming year",
            word_1="ปี",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="in front",
            word_1="ข้าง",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="panther",
            word_1="เสือ",
            word_2="ดำ",
        ),
        NaiveCompound(
            english="leopard",
            word_1="เสือ",
            word_2="ดาว",
        ),
        NaiveCompound(
            english="year of the tiger",
            word_1="ปี",
            word_2="เสือ",
        ),
        NaiveCompound(
            english="boy scout",
            word_1="ลูก",
            word_2="เสือ",
        ),
        NaiveCompound(
            english="to have a voice, to be entitled to vote",
            word_1="มี",
            word_2="เสียง",
        ),
        NaiveCompound(
            english="to dare to, to be shameless",
            word_1="มี",
            word_2="หน้า",
        ),
        NaiveCompound(
            english="to abound, to be found everywhere",
            word_1="มี",
            word_2="มาก",
        ),
        NaiveCompound(
            english="to be aged",
            word_1="มี",
            word_2="อายุ",
        ),
        NaiveCompound(
            english="to get into trouble, to quarrel",
            word_1="มี",
            word_2="เรื่อง",
        ),
        NaiveCompound(
            english="well-known",
            word_1="มี",
            word_2="ชื่อ",
        ),
        NaiveCompound(
            english="valuable, precious",
            word_1="มี",
            word_2="ค่า",
        ),
        NaiveCompound(
            english="to raise children, to bring up a child",
            word_1="เลี้ยง",
            word_2="ลูก",
        ),
        NaiveCompound(
            english="uterus, womb",
            word_1="มด",
            word_2="ลูก",
        ),
        NaiveCompound(
            english="to have children",
            word_1="มี",
            word_2="ลูก",
        ),
        NaiveCompound(
            english="son",
            word_1="ลูก",
            word_2="ชาย",
        ),
        NaiveCompound(
            english="daughter",
            word_1="ลูก",
            word_2="สาว",
        ),
        NaiveCompound(
            english="student, disciple, pupil",
            word_1="ลูก",
            word_2="ศิษย์",
        ),
        NaiveCompound(
            english="ancient, old, legendary",
            word_1="เก่า",
            word_2="ก่อน",
        ),
        NaiveCompound(
            english="older times, former times",
            word_1="ยุค",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="old friend",
            word_1="เพื่อน",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="old capital",
            word_1="กรุง",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="old generation",
            word_1="รุ่น",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="alumni, alumnus",
            word_1="ศิษย์",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="antique",
            word_1="ของ",
            word_2="เก่า"
        ),
        NaiveCompound(
            english="ancient, old, former",
            word_1="เก่า",
            word_2="แก่"
        ),
        NaiveCompound(english="national", word_1="ของ", word_2="ชาติ"),
        NaiveCompound(english="owner", word_1="เจ้า", word_2="ของ"),
        NaiveCompound(english="original", word_1="เจ้า", word_2="เก่า"),
        NaiveCompound(english="homeowner", word_1="เจ้า", word_2="บ้าน"),
        NaiveCompound(english="to build a house", word_1="สร้าง", word_2="บ้าน"),
        NaiveCompound(
            english="homeland, hometown, native village", word_1="บ้าน", word_2="เกิด"
        ),
        NaiveCompound(
            english="to be at home, stay at home", word_1="อยู่", word_2="อยู่"
        ),
        NaiveCompound(english="country, state, nation", word_1="บ้าน", word_2="เมือง"),
        NaiveCompound(
            english="villager, folk, ordinary people", word_1="ชาว", word_2="บ้าน"
        ),
        NaiveCompound(english="aging", word_1="ความ", word_2="แก่"),
        NaiveCompound(english="old people", word_1="คน", word_2="แก่"),
        NaiveCompound(english="to think of", word_1="เห็น", word_2="แก่"),
        NaiveCompound(english="courage", word_1="ความ", word_2="กล้า"),
        NaiveCompound(english="to be highly skillful in", word_1="แก่", word_2="กล้า"),
        NaiveCompound(english="steel", word_1="เหล็ก", word_2="กล้า"),
        NaiveCompound(english="iron", word_1="ธาตุ", word_2="เหล็ก"),
        NaiveCompound(english="to forge iron", word_1="ตี", word_2="เหล็ก"),
        NaiveCompound(english="water demon", word_1="เสื้อ", word_2="น้ำ"),
        NaiveCompound(english="clothes", word_1="เสื้อ", word_2="ผ้า"),
        NaiveCompound(english="Buddha", word_1="พระ", word_2="พุทธ"),
        NaiveCompound(english="butterfly", word_1="ผี", word_2="เสื้อ"),
        NaiveCompound(
            english="to offer sacrifices to a spirit", word_1="เลี้ยง", word_2="ผี"
        ),
        NaiveCompound(
            english="to offer food (to a monk)", word_1="เลี้ยง", word_2="พระ"
        ),
        NaiveCompound(english="monk on pilgrimage", word_1="พระ", word_2="ธุดงค์"),
        NaiveCompound(english="widow", word_1="แม่", word_2="หม้าย"),
        NaiveCompound(english="hen", word_1="แม่", word_2="ไก่"),
        NaiveCompound(english="ant nest", word_1="รัง", word_2="มด"),
        NaiveCompound(english="red ant", word_1="มด", word_2="แดง"),
        NaiveCompound(english="witch", word_1="แม่", word_2="มด"),
        NaiveCompound(english="nun", word_1="แม่", word_2="ชี"),
        NaiveCompound(english="housewife", word_1="แม่", word_2="บ้าน"),
        NaiveCompound(english="magnet", word_1="แม่", word_2="เหล็ก"),
        NaiveCompound(english="parents", word_1="พ่อ", word_2="แม่"),
        NaiveCompound(english="river", word_1="แม่", word_2="น้ำ"),
        NaiveCompound(english="kind-hearted woman", word_1="แม่", word_2="พระ"),
        NaiveCompound(english="Buddhist holiday", word_1="วัน", word_2="พระ"),
        NaiveCompound(english="Friday", word_1="วัน", word_2="ศุกร์"),
        NaiveCompound(english="birthday", word_1="วัน", word_2="เกิด"),
        NaiveCompound(english="Saturday", word_1="วัน", word_2="เสาร์"),
        NaiveCompound(english="venerable monk", word_1="หลวง", word_2="พ่อ"),
        NaiveCompound(english="city person", word_1="คน", word_2="เมือง"),
        NaiveCompound(english="capital city", word_1="เมือง", word_2="หลวง"),
        NaiveCompound(english="Thailand", word_1="เมือง", word_2="ไทย"),
        NaiveCompound(
            english="to be anxious, be worried", word_1="เร่า", word_2="ร้อน"
        ),
        NaiveCompound(english="tropical country", word_1="เมือง", word_2="ร้อน"),
        NaiveCompound(english="to stop, pause, stay", word_1="พัก", word_2="ไว้"),
        NaiveCompound(english="to stay overnight", word_1="พัก", word_2="อยู่"),
        NaiveCompound(english="to have a holiday", word_1="พัก", word_2="ร้อน"),
        NaiveCompound(english="summer", word_1="ฤดู", word_2="ร้อน"),
        NaiveCompound(english="hot water", word_1="น้ำ", word_2="ร้อน"),
        NaiveCompound(english="heat", word_1="ความ", word_2="ร้อน"),
        NaiveCompound(english="to worry, be anxious", word_1="ร้อน", word_2="ใจ"),
        NaiveCompound(english="local, folk, homegrown", word_1="พื้น", word_2="บ้าน"),
        NaiveCompound(english="area, district, place", word_1="พื้น", word_2="ที่"),
        NaiveCompound(english="surface of the water", word_1="พื้น", word_2="น้ำ"),
        NaiveCompound(english="the Earth's surface", word_1="พื้น", word_2="โลก"),
        NaiveCompound(english="pole (north, south)", word_1="ขั้ว", word_2="โลก"),
        NaiveCompound(english="world population", word_1="ชาว", word_2="โลก"),
        NaiveCompound(english="world war", word_1="สงคราม", word_2="โลก"),
        NaiveCompound(english="global warming", word_1="โลก", word_2="ร้อน"),
        NaiveCompound(english="worldwide", word_1="ทั่ว", word_2="โลก"),
        NaiveCompound(english="worldly, material, fleshy", word_1="ของ", word_2="โลก"),
        NaiveCompound(english="leaf", word_1="ใบ", word_2="ไม้"),
        NaiveCompound(english="around the world", word_1="รอบ", word_2="โลก"),
        NaiveCompound(english="tree", word_1="ไม้", word_2="ใหญ่"),
        NaiveCompound(english="majority", word_1="ส่วน", word_2="ใหญ่"),
        NaiveCompound(english="headmaster", word_1="ครู", word_2="ใหญ่"),
        NaiveCompound(
            english="to be intimate / to know the mind", word_1="รู้", word_2="ใจ"
        ),
        NaiveCompound(english="user", word_1="ผู้", word_2="ใช้"),
        NaiveCompound(english="adult, senior, elder", word_1="ผู้", word_2="ใหญ่"),
        NaiveCompound(
            english="patient, sufferer, sick person", word_1="ผู้", word_2="ป่วย"
        ),
        NaiveCompound(english="leader, chief, captain", word_1="ผู้", word_2="นำ"),
        NaiveCompound(english="man", word_1="ผู้", word_2="ชาย"),
        NaiveCompound(english="woman", word_1="ผู้", word_2="หญิง"),
        NaiveCompound(english="to risk, jeopardize", word_1="เสี่ยง", word_2="ชีวิต"),
        NaiveCompound(
            english="knowledgeable people, well-informed people",
            word_1="ผู้",
            word_2="รู้",
        ),
        NaiveCompound(english="to let someone know", word_1="ให้", word_2="รู้"),
        NaiveCompound(english="to know (someone)", word_1="รู้", word_2="จัก"),
        NaiveCompound(
            english="knowledge, information, awareness", word_1="ความ", word_2="รู้"
        ),
        NaiveCompound(english="to leave the monkhood", word_1="ลา", word_2="สึก"),
        NaiveCompound(english="to feel, touch", word_1="รู้", word_2="สึก"),
        NaiveCompound(english="all around", word_1="รอบ", word_2="ตัว"),
        NaiveCompound(english="to be aware, conscious of", word_1="รู้", word_2="ตัว"),
        NaiveCompound(english="to take the risk", word_1="ลอง", word_2="เสี่ยง"),
        NaiveCompound(english="to try out", word_1="ลอง", word_2="ดู"),
        NaiveCompound(
            english="to reproduce, make a copy, imitate", word_1="จำ", word_2="ลอง"
        ),
        NaiveCompound(english="to test, experiment, try", word_1="ลอง", word_2="ทำ"),
        NaiveCompound(
            english="to come to terms with, to accept", word_1="ทำ", word_2="ใจ"
        ),
        NaiveCompound(
            english="to make a mistake, do something wrong", word_1="ทำ", word_2="ผิด"
        ),
        NaiveCompound(english="to cook", word_1="ทำ", word_2="อาหาร"),
        NaiveCompound(english="to farm", word_1="ทำ", word_2="นา"),
        NaiveCompound(english="to imitate, copy / to obey", word_1="ทำ", word_2="ตาม"),
        NaiveCompound(english="to hurt, to do harm", word_1="ทำ", word_2="ร้าย"),
        NaiveCompound(english="to cause trouble", word_1="ทำ", word_2="ความ"),
        NaiveCompound(english="to pretend, feign", word_1="ทำ", word_2="เป็น"),
        NaiveCompound(english="to make merit", word_1="ทำ", word_2="บุญ"),
        NaiveCompound(english="to work", word_1="ทำ", word_2="งาน"),
        NaiveCompound(
            english="to cause, to make somebody do something", word_1="ทำ", word_2="ให้"
        ),
        NaiveCompound(
            english="to behave, conduct oneself, act", word_1="ทำ", word_2="ตัว"
        ),
        NaiveCompound(english="oneself, ourselves", word_1="ตัว", word_2="เอง"),
        NaiveCompound(english="to be stable, steady", word_1="อยู่", word_2="ตัว"),
        NaiveCompound(english="to survive, exist", word_1="อยู่", word_2="รอด"),
        NaiveCompound(
            english="to learn by heart, memorize", word_1="ขึ้น", word_2="ใจ"
        ),
        NaiveCompound(english="to depend on, rely on", word_1="ขึ้น", word_2="อยู่"),
        NaiveCompound(english="to live, reside", word_1="อาศัย", word_2="อยู่"),
        NaiveCompound(english="address", word_1="ที่", word_2="อยู่"),
        NaiveCompound(
            english="like, as, such as, as if", word_1="เหมือน", word_2="กับ"
        ),
        NaiveCompound(english="the same as", word_1="เดียว", word_2="กับ"),
        NaiveCompound(
            english="to be with, stay with, be with", word_1="อยู่", word_2="กับ"
        ),
        NaiveCompound(english="about, regarding", word_1="เกี่ยว", word_2="กับ"),
        NaiveCompound(english="to go to the toilet", word_1="ไป", word_2="ทุ่ง"),
        NaiveCompound(english="to go overseas", word_1="ไป", word_2="นอก"),
        NaiveCompound(english="going", word_1="การ", word_2="ไป"),
        NaiveCompound(english="to go with, accompany", word_1="ไป", word_2="กับ"),
        NaiveCompound(english="to go to see, visit, meet", word_1="ไป", word_2="หา"),
        NaiveCompound(english="to go and see", word_1="ไป", word_2="ดู"),
        NaiveCompound(english="to arrive at, to reach", word_1="ไป", word_2="ถึง"),
        NaiveCompound(english="Saturn", word_1="ดาว", word_2="เสาร์"),
        NaiveCompound(
            english="to be rejected, to be defeated, be settled",
            word_1="ตก",
            word_2="ไป",
        ),
        NaiveCompound(english="to angle, to fish", word_1="ตก", word_2="ปลา"),
        NaiveCompound(english="to be startled, shocked", word_1="ตก", word_2="ใจ"),
        NaiveCompound(english="rain", word_1="ฝน", word_2="ตก"),
        NaiveCompound(english="waterfall", word_1="น้ำ", word_2="ตก"),
        NaiveCompound(english="meteor, shooting star", word_1="ดาว", word_2="ตก"),
        NaiveCompound(english="satellite", word_1="ดาว", word_2="เทียม"),
        NaiveCompound(english="constellation", word_1="กลุ่ม", word_2="ดาว"),
        NaiveCompound(english="crowd, group of people", word_1="กลุ่ม", word_2="คน"),
        NaiveCompound(english="to form into groups", word_1="จัด", word_2="กลุ่ม"),
        NaiveCompound(english="to publish", word_1="จัด", word_2="พิมพ์"),
        NaiveCompound(english="to worry, think too much", word_1="คิด", word_2="มาก"),
        NaiveCompound(english="to manage, deal, handle", word_1="จัด", word_2="การ"),
        NaiveCompound(english="to want, need, require", word_1="ต้อง", word_2="การ"),
        NaiveCompound(
            english="to succeed, accomplish, complete", word_1="เป็น", word_2="การ"
        ),
        NaiveCompound(english="thought, thinking", word_1="การ", word_2="คิด"),
        NaiveCompound(english="thought, idea, notion", word_1="ความ", word_2="คิด"),
        NaiveCompound(english="to think that", word_1="คิด", word_2="ว่า"),
        NaiveCompound(
            english="to comment, discuss, criticize", word_1="คิด", word_2="เห็น"
        ),
        NaiveCompound(
            english="to realize, become aware of, comprehend",
            word_1="คิด",
            word_2="ได้",
        ),
        NaiveCompound(english="possibly, likely, maybe", word_1="เป็น", word_2="ได้"),
        NaiveCompound(english="memory, remembrance", word_1="ความ", word_2="จำ"),
        NaiveCompound(english="to remember", word_1="จำ", word_2="ได้"),
        NaiveCompound(english="to understand", word_1="เข้า", word_2="ใจ"),
        NaiveCompound(english="to understand", word_1="เข้า", word_2="ใจ"),
        NaiveCompound(english="good person/darling, honey", word_1="คน", word_2="ดี"),
        NaiveCompound(english="very good, excellent", word_1="ดี", word_2="มาก"),
        NaiveCompound(english="lucky/good luck!", word_1="โชค", word_2="ดี"),
        NaiveCompound(english="no matter, whatever", word_1="ก็", word_2="ตาม"),
        NaiveCompound(english="to be quite good, not bad", word_1="ก็", word_2="ดี"),
        NaiveCompound(english="ok, all right, fine", word_1="ก็", word_2="ได้"),
        NaiveCompound(
            english="audience, spectator, onlooker", word_1="คน", word_2="ดู"
        ),
        NaiveCompound(english="to look good", word_1="ดู", word_2="ดี"),
        NaiveCompound(english="to be nice", word_1="ใจ", word_2="ดี"),
        NaiveCompound(english="to be glad", word_1="ยิน", word_2="ดี"),
        NaiveCompound(english="to hear", word_1="ได้", word_2="ยิน"),
    ]


# def get_links_from_city_word(current_word: str, al):
#     city_words = get_city_words(al)
#     near_city_words = []
#     for aggregate in AGGREGATES:
#         if current_word in aggregate["words"]:
#             for word in aggregate["words"]:
#                 if word != current_word:
#                     near_city_words.append({
#                         "english": aggregate["english"],
#                         "thai": aggregate["thai"],
#                         "words": aggregate["words"],
#                         "city": city_words[word],
#                     })
#     # al.aggregates = near_city_words
#     for near_city_word in near_city_words:
#         print(near_city_word)
