from dataclasses import dataclass

from overworld import Ma


@dataclass
class NaiveUnit:
    map: Ma = None
    x: int = 0
    y: int = 0


@dataclass
class Compound:
    english: str
    thai: str
    word_1: str
    word_2: str


def get_naive_units(al):
    return {
        "คน": NaiveUnit(
            map=al.mas.chaiyaphum,
            x=800,
            y=711,
        ),
        "ดี": NaiveUnit(
            map=al.mas.chumphae,
            x=818,
            y=622,
        ),
        "ดู": NaiveUnit(
            map=al.mas.lomsak,
            x=818,
            y=622,
        ),
        "ใจ": NaiveUnit(
            map=al.mas.lomsak,
            x=669,
            y=618,
        ),
        "ยิน": NaiveUnit(
            map=al.mas.kasetsombum,
            x=790,
            y=655,
        ),
        "โชค": NaiveUnit(),
        "มาก": NaiveUnit(),
        "ได้": NaiveUnit(),
        "ก็": NaiveUnit(),
        "ตาม": NaiveUnit(),
        "เข้า": NaiveUnit(),
        "จำ": NaiveUnit(),
        "ความ": NaiveUnit(),
        "เป็น": NaiveUnit(),
        "คิด": NaiveUnit(),
        "เห็น": NaiveUnit(),
        "ว่า": NaiveUnit(),
        "การ": NaiveUnit(),
        "ต้อง": NaiveUnit(),
        "จัด": NaiveUnit(),
        "พิมพ์": NaiveUnit(),
        "กลุ่ม": NaiveUnit(),
        "ดาว": NaiveUnit(),
        "เทียม": NaiveUnit(),
        "ตก": NaiveUnit(),
        "น้ำ": NaiveUnit(),
        "ฝน": NaiveUnit(),
        "ปลา": NaiveUnit(),
        "ไป": NaiveUnit(),
        "เสาร์": NaiveUnit(),
        "ถึง": NaiveUnit(),
        "กับ": NaiveUnit(),
        "หา": NaiveUnit(),
        "นอก": NaiveUnit(),
        "ทุ่ง": NaiveUnit(),
        "เกี่ยว": NaiveUnit(),
        "อยู่": NaiveUnit(),
        "เดียว": NaiveUnit(),
        "เหมือน": NaiveUnit(),
        "ที่": NaiveUnit(),
        "อาศัย": NaiveUnit(),
        "ขึ้น": NaiveUnit(),
        "รอด": NaiveUnit(),
        "เอง": NaiveUnit(),
        "ทำ": NaiveUnit(),
        "ให้": NaiveUnit(),
        "งาน": NaiveUnit(),
        "บุญ": NaiveUnit(),
        "ร้าย": NaiveUnit(),
        "นา": NaiveUnit(),
        "อาหาร": NaiveUnit(),
        "ผิด": NaiveUnit(),
        "ลอง": NaiveUnit(),
        "เสี่ยง": NaiveUnit(),
        "รู้": NaiveUnit(),
        "รอบ": NaiveUnit(),
        "สึก": NaiveUnit(),
        "ลา": NaiveUnit(),
        "จัก": NaiveUnit(),
        "ผู้": NaiveUnit(),
        "ชีวิต": NaiveUnit(),
        "หญิง": NaiveUnit(),
        "ชาย": NaiveUnit(),
        "นำ": NaiveUnit(),
        "ป่วย": NaiveUnit(),
        "ใหญ่": NaiveUnit(),
        "ใช้": NaiveUnit(),
        "ครู": NaiveUnit(),
        "ส่วน": NaiveUnit(),
        "ไม้": NaiveUnit(),
        "โลก": NaiveUnit(),
        "ใบ": NaiveUnit(),
        "ตัว": NaiveUnit(),
        "ของ": NaiveUnit(),
        "ทั่ว": NaiveUnit(),
        "ร้อน": NaiveUnit(),
        "สงคราม": NaiveUnit(),
        "ชาว": NaiveUnit(),
        "ขั้ว": NaiveUnit(),
        "พื้น": NaiveUnit(),
        "บ้าน": NaiveUnit(),
        "ฤดู": NaiveUnit(),
        "พัก": NaiveUnit(),
        "ไว้": NaiveUnit(),
        "เมือง": NaiveUnit(),
        "เร่า": NaiveUnit(),
        "ไทย": NaiveUnit(),
        "หลวง": NaiveUnit(),
        "พ่อ": NaiveUnit(),
        "วัน": NaiveUnit(),
        "เกิด": NaiveUnit(),
        "ศุกร์": NaiveUnit(),
        "พระ": NaiveUnit(),
        "แม่": NaiveUnit(),
        "เหล็ก": NaiveUnit(),
        "ชี": NaiveUnit(),
        "มด": NaiveUnit(),
        "แดง": NaiveUnit(),
        "รัง": NaiveUnit(),
        "ไก่": NaiveUnit(),
        "หม้าย": NaiveUnit(),
        "ธุดงค์": NaiveUnit(),
        "เลี้ยง": NaiveUnit(),
        "ผี": NaiveUnit(),
        "เสื้อ": NaiveUnit(),
        "พุทธ": NaiveUnit(),
        "ผ้า": NaiveUnit(),
        "ตี": NaiveUnit(),
        "ธาตุ": NaiveUnit(),
        "กล้า": NaiveUnit(),
        "แก่": NaiveUnit(),
        "สร้าง": NaiveUnit(),
        "เจ้า": NaiveUnit(),
        "เก่า": NaiveUnit(),
        "ชาติ": NaiveUnit(),
    }


def get_compounds():
    return [
        Compound(
            english="national",
            thai="ของชาติ",
            word_1="ของ",
            word_2="ชาติ",
        ),
        Compound(
            english="owner",
            thai="เจ้าของ",
            word_1="เจ้า",
            word_2="ของ",
        ),
        Compound(
            english="original",
            thai="เจ้าเก่า",
            word_1="เจ้า",
            word_2="เก่า",
        ),
        Compound(
            english="homeowner",
            thai="เจ้าบ้าน",
            word_1="เจ้า",
            word_2="บ้าน",
        ),
        Compound(
            english="to build a house",
            thai="สร้างบ้าน",
            word_1="สร้าง",
            word_2="บ้าน",
        ),
        Compound(
            english="homeland, hometown, native village",
            thai="บ้านเกิด",
            word_1="บ้าน",
            word_2="เกิด",
        ),
        Compound(
            english="to be at home, stay at home",
            thai="อยู่บ้าน",
            word_1="อยู่",
            word_2="อยู่",
        ),
        Compound(
            english="country, state, nation",
            thai="บ้านเมือง",
            word_1="บ้าน",
            word_2="เมือง",
        ),
        Compound(
            english="villager, folk, ordinary people",
            thai="ชาวบ้าน",
            word_1="ชาว",
            word_2="บ้าน",
        ),
        Compound(
            english="aging",
            thai="ความแก่",
            word_1="ความ",
            word_2="แก่",
        ),
        Compound(
            english="old people",
            thai="คนแก่",
            word_1="คน",
            word_2="แก่",
        ),
        Compound(
            english="to think of",
            thai="เห็นแก่",
            word_1="เห็น",
            word_2="แก่",
        ),
        Compound(
            english="courage",
            thai="ความกล้า",
            word_1="ความ",
            word_2="กล้า",
        ),
        Compound(
            english="to be highly skillful in",
            thai="แก่กล้า",
            word_1="แก่",
            word_2="กล้า",
        ),
        Compound(
            english="steel",
            thai="เหล็กกล้า",
            word_1="เหล็ก",
            word_2="กล้า",
        ),
        Compound(
            english="iron",
            thai="ธาตุเหล็ก",
            word_1="ธาตุ",
            word_2="เหล็ก",
        ),
        Compound(
            english="to forge iron",
            thai="ตีเหล็ก",
            word_1="ตี",
            word_2="เหล็ก",
        ),
        Compound(
            english="water demon",
            thai="เสื้อน้ำ",
            word_1="เสื้อ",
            word_2="น้ำ",
        ),
        Compound(
            english="clothes",
            thai="เสื้อผ้า",
            word_1="เสื้อ",
            word_2="ผ้า",
        ),
        Compound(
            english="Buddha",
            thai="พระพุทธ",
            word_1="พระ",
            word_2="พุทธ",
        ),
        Compound(
            english="butterfly",
            thai="ผีเสื้อ",
            word_1="ผี",
            word_2="เสื้อ",
        ),
        Compound(
            english="to offer sacrifices to a spirit",
            thai="เลี้ยงผี",
            word_1="เลี้ยง",
            word_2="ผี",
        ),
        Compound(
            english="to offer food (to a monk)",
            thai="เลี้ยงพระ",
            word_1="เลี้ยง",
            word_2="พระ",
        ),
        Compound(
            english="monk on pilgrimage",
            thai="พระธุดงค์",
            word_1="พระ",
            word_2="ธุดงค์",
        ),
        Compound(
            english="widow",
            thai="แม่หม้าย",
            word_1="แม่",
            word_2="หม้าย",
        ),
        Compound(
            english="hen",
            thai="แม่ไก่",
            word_1="แม่",
            word_2="ไก่",
        ),
        Compound(
            english="ant nest",
            thai="รังมด",
            word_1="รัง",
            word_2="มด",
        ),
        Compound(
            english="red ant",
            thai="มดแดง",
            word_1="มด",
            word_2="แดง",
        ),
        Compound(
            english="witch",
            thai="แม่มด",
            word_1="แม่",
            word_2="มด",
        ),
        Compound(
            english="nun",
            thai="แม่ชี",
            word_1="แม่",
            word_2="ชี",
        ),
        Compound(
            english="housewife",
            thai="แม่บ้าน",
            word_1="แม่",
            word_2="บ้าน",
        ),
        Compound(
            english="magnet",
            thai="แม่เหล็ก",
            word_1="แม่",
            word_2="เหล็ก",
        ),
        Compound(
            english="parents",
            thai="พ่อแม่",
            word_1="พ่อ",
            word_2="แม่",
        ),
        Compound(
            english="river",
            thai="แม่น้ำ",
            word_1="แม่",
            word_2="น้ำ",
        ),
        Compound(
            english="kind-hearted woman",
            thai="แม่พระ",
            word_1="แม่",
            word_2="พระ",
        ),
        Compound(
            english="Buddhist holiday",
            thai="วันพระ",
            word_1="วัน",
            word_2="พระ",
        ),
        Compound(
            english="Friday",
            thai="วันศุกร์",
            word_1="วัน",
            word_2="ศุกร์",
        ),
        Compound(
            english="birthday",
            thai="วันเกิด",
            word_1="วัน",
            word_2="เกิด",
        ),
        Compound(
            english="Saturday",
            thai="วันเสาร์",
            word_1="วัน",
            word_2="เสาร์",
        ),
        Compound(
            english="venerable monk",
            thai="หลวงพ่อ",
            word_1="หลวง",
            word_2="พ่อ",
        ),
        Compound(
            english="city person",
            thai="คนเมือง",
            word_1="คน",
            word_2="เมือง",
        ),
        Compound(
            english="capital city",
            thai="เมืองหลวง",
            word_1="เมือง",
            word_2="หลวง",
        ),
        Compound(
            english="Thailand",
            thai="เมืองไทย",
            word_1="เมือง",
            word_2="ไทย",
        ),
        Compound(
            english="to be anxious, be worried",
            thai="เร่าร้อน",
            word_1="เร่า",
            word_2="ร้อน",
        ),
        Compound(
            english="tropical country",
            thai="เมืองร้อน",
            word_1="เมือง",
            word_2="ร้อน",
        ),
        Compound(
            english="to stop, pause, stay",
            thai="พักไว้",
            word_1="พัก",
            word_2="ไว้",
        ),
        Compound(
            english="to stay overnight",
            thai="พักอยู่",
            word_1="พัก",
            word_2="อยู่",
        ),
        Compound(
            english="to have a holiday",
            thai="พักร้อน",
            word_1="พัก",
            word_2="ร้อน",
        ),
        Compound(
            english="summer",
            thai="ฤดูร้อน",
            word_1="ฤดู",
            word_2="ร้อน",
        ),
        Compound(
            english="hot water",
            thai="น้ำร้อน",
            word_1="น้ำ",
            word_2="ร้อน",
        ),
        Compound(
            english="heat",
            thai="ความร้อน",
            word_1="ความ",
            word_2="ร้อน",
        ),
        Compound(
            english="to worry, be anxious",
            thai="ร้อนใจ",
            word_1="ร้อน",
            word_2="ใจ",
        ),
        Compound(
            english="local, folk, homegrown",
            thai="พื้นบ้าน",
            word_1="พื้น",
            word_2="บ้าน",
        ),
        Compound(
            english="area, district, place",
            thai="พื้นที่",
            word_1="พื้น",
            word_2="ที่",
        ),
        Compound(
            english="surface of the water",
            thai="พื้นน้ำ",
            word_1="พื้น",
            word_2="น้ำ",
        ),
        Compound(
            english="the Earth's surface",
            thai="พื้นโลก",
            word_1="พื้น",
            word_2="โลก",
        ),
        Compound(
            english="pole (north, south)",
            thai="ขั้วโลก",
            word_1="ขั้ว",
            word_2="โลก",
        ),
        Compound(
            english="world population",
            thai="ชาวโลก",
            word_1="ชาว",
            word_2="โลก",
        ),
        Compound(
            english="world war",
            thai="สงครามโลก",
            word_1="สงคราม",
            word_2="โลก",
        ),
        Compound(
            english="global warming",
            thai="โลกร้อน",
            word_1="โลก",
            word_2="ร้อน",
        ),
        Compound(
            english="worldwide",
            thai="ทั่วโลก",
            word_1="ทั่ว",
            word_2="โลก",
        ),
        Compound(
            english="worldly, material, fleshy",
            thai="ของโลก",
            word_1="ของ",
            word_2="โลก",
        ),
        Compound(
            english="leaf",
            thai="ใบไม้",
            word_1="ใบ",
            word_2="ไม้",
        ),
        Compound(
            english="around the world",
            thai="รอบโลก",
            word_1="รอบ",
            word_2="โลก",
        ),
        Compound(
            english="tree",
            thai="ไม้ใหญ่",
            word_1="ไม้",
            word_2="ใหญ่",
        ),
        Compound(
            english="majority",
            thai="ส่วนใหญ่",
            word_1="ส่วน",
            word_2="ใหญ่",
        ),
        Compound(
            english="headmaster",
            thai="ครูใหญ่",
            word_1="ครู",
            word_2="ใหญ่",
        ),
        Compound(
            english="to be intimate / to know the mind",
            thai="รู้ใจ",
            word_1="รู้",
            word_2="ใจ",
        ),
        Compound(
            english="user",
            thai="ผู้ใช้",
            word_1="ผู้",
            word_2="ใช้",
        ),
        Compound(
            english="adult, senior, elder",
            thai="ผู้ใหญ่",
            word_1="ผู้",
            word_2="ใหญ่",
        ),
        Compound(
            english="patient, sufferer, sick person",
            thai="ผู้ป่วย",
            word_1="ผู้",
            word_2="ป่วย",
        ),
        Compound(
            english="leader, chief, captain",
            thai="ผู้นำ",
            word_1="ผู้",
            word_2="นำ",
        ),
        Compound(
            english="man",
            thai="ผู้ชาย",
            word_1="ผู้",
            word_2="ชาย",
        ),
        Compound(
            english="woman",
            thai="ผู้หญิง",
            word_1="ผู้",
            word_2="หญิง",
        ),
        Compound(
            english="to risk, jeopardize",
            thai="เสี่ยงชีวิต",
            word_1="เสี่ยง",
            word_2="ชีวิต",
        ),
        Compound(
            english="knowledgeable people, well-informed people",
            thai="ผู้รู้",
            word_1="ผู้",
            word_2="รู้",
        ),
        Compound(
            english="to let someone know",
            thai="ให้รู้",
            word_1="ให้",
            word_2="รู้",
        ),
        Compound(
            english="to know (someone)",
            thai="รู้จัก",
            word_1="รู้",
            word_2="จัก",
        ),
        Compound(
            english="knowledge, information, awareness",
            thai="ความรู้",
            word_1="ความ",
            word_2="รู้",
        ),
        Compound(
            english="to leave the monkhood",
            thai="ลาสึก",
            word_1="ลา",
            word_2="สึก",
        ),
        Compound(
            english="to feel, touch",
            thai="รู้สึก",
            word_1="รู้",
            word_2="สึก",
        ),
        Compound(
            english="all around",
            thai="รอบตัว",
            word_1="รอบ",
            word_2="ตัว",
        ),
        Compound(
            english="to be aware, conscious of",
            thai="รู้ตัว",
            word_1="รู้",
            word_2="ตัว",
        ),
        Compound(
            english="to take the risk",
            thai="ลองเสี่ยง",
            word_1="ลอง",
            word_2="เสี่ยง",
        ),
        Compound(
            english="to try out",
            thai="ลองดู",
            word_1="ลอง",
            word_2="ดู",
        ),
        Compound(
            english="to reproduce, make a copy, imitate",
            thai="จำลอง",
            word_1="จำ",
            word_2="ลอง",
        ),
        Compound(
            english="to test, experiment, try",
            thai="ลองทำ",
            word_1="ลอง",
            word_2="ทำ",
        ),
        Compound(
            english="to come to terms with, to accept",
            thai="ทำใจ",
            word_1="ทำ",
            word_2="ใจ",
        ),
        Compound(
            english="to make a mistake, do something wrong",
            thai="ทำผิด",
            word_1="ทำ",
            word_2="ผิด",
        ),
        Compound(
            english="to cook",
            thai="ทำอาหาร",
            word_1="ทำ",
            word_2="อาหาร",
        ),
        Compound(
            english="to farm",
            thai="ทำนา",
            word_1="ทำ",
            word_2="นา",
        ),
        Compound(
            english="to imitate, copy / to obey",
            thai="ทำตาม",
            word_1="ทำ",
            word_2="ตาม",
        ),
        Compound(
            english="to hurt, to do harm",
            thai="ทำร้าย",
            word_1="ทำ",
            word_2="ร้าย",
        ),
        Compound(
            english="to cause trouble",
            thai="ทำความ",
            word_1="ทำ",
            word_2="ความ",
        ),
        Compound(
            english="to pretend, feign",
            thai="ทำเป็น",
            word_1="ทำ",
            word_2="เป็น",
        ),
        Compound(
            english="to make merit",
            thai="ทำบุญ",
            word_1="ทำ",
            word_2="บุญ",
        ),
        Compound(
            english="to work",
            thai="ทำงาน",
            word_1="ทำ",
            word_2="งาน",
        ),
        Compound(
            english="to cause, to make somebody do something",
            thai="ทำให้",
            word_1="ทำ",
            word_2="ให้",
        ),
        Compound(
            english="to behave, conduct oneself, act",
            thai="ทำตัว",
            word_1="ทำ",
            word_2="ตัว",
        ),
        Compound(
            english="oneself, ourselves",
            thai="ตัวเอง",
            word_1="ตัว",
            word_2="เอง",
        ),
        Compound(
            english="to be stable, steady",
            thai="อยู่ตัว",
            word_1="อยู่",
            word_2="ตัว",
        ),
        Compound(
            english="to survive, exist",
            thai="อยู่รอด",
            word_1="อยู่",
            word_2="รอด",
        ),
        Compound(
            english="to learn by heart, memorize",
            thai="ขึ้นใจ",
            word_1="ขึ้น",
            word_2="ใจ",
        ),
        Compound(
            english="to depend on, rely on",
            thai="ขึ้นอยู่",
            word_1="ขึ้น",
            word_2="อยู่",
        ),
        Compound(
            english="to live, reside",
            thai="อาศัยอยู่",
            word_1="อาศัย",
            word_2="อยู่",
        ),
        Compound(
            english="address",
            thai="ที่อยู่",
            word_1="ที่",
            word_2="อยู่",
        ),
        Compound(
            english="like, as, such as, as if",
            thai="เหมือนกับ",
            word_1="เหมือน",
            word_2="กับ",
        ),
        Compound(
            english="the same as",
            thai="เดียวกับ",
            word_1="เดียว",
            word_2="กับ",
        ),
        Compound(
            english="to be with, stay with, be with",
            thai="อยู่กับ",
            word_1="อยู่",
            word_2="กับ",
        ),
        Compound(
            english="about, regarding",
            thai="เกี่ยวกับ",
            word_1="เกี่ยว",
            word_2="กับ",
        ),
        Compound(
            english="to go to the toilet",
            thai="ไปทุ่ง",
            word_1="ไป",
            word_2="ทุ่ง",
        ),
        Compound(
            english="to go overseas",
            thai="ไปนอก",
            word_1="ไป",
            word_2="นอก",
        ),
        Compound(
            english="going",
            thai="การไป",
            word_1="การ",
            word_2="ไป",
        ),
        Compound(
            english="to go with, accompany",
            thai="ไปกับ",
            word_1="ไป",
            word_2="กับ",
        ),
        Compound(
            english="to go to see, visit, meet",
            thai="ไปหา",
            word_1="ไป",
            word_2="หา",
        ),
        Compound(
            english="to go and see",
            thai="ไปดู",
            word_1="ไป",
            word_2="ดู",
        ),
        Compound(
            english="to arrive at, to reach",
            thai="ไปถึง",
            word_1="ไป",
            word_2="ถึง",
        ),
        Compound(
            english="Saturn",
            thai="ดาวเสาร์",
            word_1="ดาว",
            word_2="เสาร์",
        ),
        Compound(
            english="to be rejected, to be defeated, be settled",
            thai="ตกไป",
            word_1="ตก",
            word_2="ไป",
        ),
        Compound(
            english="to angle, to fish",
            thai="ตกปลา",
            word_1="ตก",
            word_2="ปลา",
        ),
        Compound(
            english="to be startled, shocked",
            thai="ตกใจ",
            word_1="ตก",
            word_2="ใจ",
        ),
        Compound(
            english="rain",
            thai="ฝนตก",
            word_1="ฝน",
            word_2="ตก",
        ),
        Compound(
            english="waterfall",
            thai="น้ำตก",
            word_1="น้ำ",
            word_2="ตก",
        ),
        Compound(
            english="meteor, shooting star",
            thai="ดาวตก",
            word_1="ดาว",
            word_2="ตก",
        ),
        Compound(
            english="satellite",
            thai="ดาวเทียม",
            word_1="ดาว",
            word_2="เทียม",
        ),
        Compound(
            english="constellation",
            thai="กลุ่มดาว",
            word_1="กลุ่ม",
            word_2="ดาว",
        ),
        Compound(
            english="crowd, group of people",
            thai="กลุ่มคน",
            word_1="กลุ่ม",
            word_2="คน",
        ),
        Compound(
            english="to form into groups",
            thai="จัดกลุ่ม",
            word_1="จัด",
            word_2="กลุ่ม",
        ),
        Compound(
            english="to publish",
            thai="จัดพิมพ์",
            word_1="จัด",
            word_2="พิมพ์",
        ),
        Compound(
            english="to worry, think too much",
            thai="คิดมาก",
            word_1="คิด",
            word_2="มาก",
        ),
        Compound(
            english="to manage, deal, handle",
            thai="จัดการ",
            word_1="จัด",
            word_2="การ",
        ),
        Compound(
            english="to want, need, require",
            thai="ต้องการ",
            word_1="ต้อง",
            word_2="การ",
        ),
        Compound(
            english="to succeed, accomplish, complete",
            thai="เป็นการ",
            word_1="เป็น",
            word_2="การ",
        ),
        Compound(
            english="thought, thinking",
            thai="การคิด",
            word_1="การ",
            word_2="คิด",
        ),
        Compound(
            english="thought, idea, notion",
            thai="ความคิด",
            word_1="ความ",
            word_2="คิด",
        ),
        Compound(
            english="to think that",
            thai="คิดว่า",
            word_1="คิด",
            word_2="ว่า",
        ),
        Compound(
            english="to comment, discuss, criticize",
            thai="คิดเห็น",
            word_1="คิด",
            word_2="เห็น",
        ),
        Compound(
            english="to realize, become aware of, comprehend",
            thai="คิดได้",
            word_1="คิด",
            word_2="ได้",
        ),
        Compound(
            english="possibly, likely, maybe",
            thai="เป็นได้",
            word_1="เป็น",
            word_2="ได้",
        ),
        Compound(
            english="memory, remembrance",
            thai="ความจำ",
            word_1="ความ",
            word_2="จำ",
        ),
        Compound(
            english="to remember",
            thai="จำได้",
            word_1="จำ",
            word_2="ได้",
        ),
        Compound(
            english="to understand",
            thai="เข้า_ใจ",
            word_1="เข้า",
            word_2="ใจ",
        ),
        Compound(
            english="to understand",
            thai="เข้า_ใจ",
            word_1="เข้า",
            word_2="ใจ",
        ),
        Compound(
            english="good person/darling, honey",
            thai="คน_ดี",
            word_1="คน",
            word_2="ดี",
        ),
        Compound(
            english="very good, excellent",
            thai="ดี_มาก",
            word_1="ดี",
            word_2="มาก",
        ),
        Compound(
            english="lucky/good luck!",
            thai="โชค_ดี",
            word_1="โชค",
            word_2="ดี",
        ),
        Compound(
            english="no matter, whatever",
            thai="ก็_ตาม",
            word_1="ก็",
            word_2="ตาม",
        ),
        Compound(
            english="to be quite good, not bad",
            thai="ก็_ดี",
            word_1="ก็",
            word_2="ดี",
        ),
        Compound(
            english="ok, all right, fine",
            thai="ก็_ได้",
            word_1="ก็",
            word_2="ได้",
        ),
        Compound(
            english="audience, spectator, onlooker",
            thai="คน_ดู",
            word_1="คน",
            word_2="ดู",
        ),
        Compound(
            english="to look good",
            thai="ดู_ดี",
            word_1="ดู",
            word_2="ดี",
        ),
        Compound(
            english="to be nice",
            thai="ใจ_ดี",
            word_1="ใจ",
            word_2="ดี",
        ),
        Compound(
            english="to be glad",
            thai="ยิน_ดี",
            word_1="ยิน",
            word_2="ดี",
        ),
        Compound(
            english="to hear",
            thai="ได้_ยิน",
            word_1="ได้",
            word_2="ยิน",
        ),
    ]


# def get_links_from_city_word(current_word: str, al):
#     city_words = get_city_words(al)
#     near_city_words = []
#     for aggregate in AGGREGATES:
#         if current_word in aggregate["words"]:
#             for word in aggregate["words"]:
#                 if word != current_word:
#                     near_city_words.append({
#                         "english": aggregate["english"],
#                         "thai": aggregate["thai"],
#                         "words": aggregate["words"],
#                         "city": city_words[word],
#                     })
#     # al.aggregates = near_city_words
#     for near_city_word in near_city_words:
#         print(near_city_word)
